nifty_test = ['PGEL']
nifty_vcp = ['INFOBEAN',	'SEAMECLTD',	'BLISSGVS',	'GPIL',	'KERNEX',	'NGLFINE',	'SOUTHBANK',
'SMLMAH',	'GRAPHITE',	'SIRCA',	'JPOLYINVST',	'JAYBARMARU',	'SYRMA',	'ANURAS',
'RAMCOSYS',	'IIFLCAPS',	'ACUTAAS',	'INDIAGLYCO',	'TI',	'DOLPHIN',	'DREDGECORP',
'TDPOWERSYS',	'RACLGEAR',	'JKTYRE',	'MCX',	'DYNAMATECH',	'SCI',	'CEATLTD',
'SANSERA',	'FIEMIND',	'POONAWALLA',	'WCIL',	'TVSSRICHAK',	'KIRLOSENG',	'THANGAMAYL',
'MTARTECH',	'CUPID',	'MUFIN',	'BLACKBUCK',	'PTCIL',	'MIRCELECTR',	'SENORES',
'TMB',	'UNIPARTS',	'CARYSIL',	'SANDHAR',	'GMBREW',	'INDSWFTLAB',	'RISHABH',
'FORCEMOT',	'RAJRATAN',	'KRISHANA',	'MBAPL',	'DCBBANK',	'SBC',	'UJJIVANSFB',
'SABTNL',	'JAYNECOIND',	'TFCILTD',	'INDIACEM',	'CCL',	'MRPL',	'CRAFTSMAN',
'UEL',	'AVANTIFEED',	'LGBBROSLTD',	'BAJAJCON',	'BBOX',	'SHRIPISTON',	'GOODLUCK',
'GODAVARIB',	'RBLBANK',	'VSTTILLERS',	'NORTHARC',	'SILVERTUC',	'NAVINFLUOR',	
'SMSPHARMA',	'CHENNPETRO',	'CUB',	'APEX',	'SHARDACROP',	'ASIANTILES',	
'PRECWIRE',	'LUMAXTECH',	'IMFA',	'SJS',	'KARURVYSYA',	'RICOAUTO',	
'KINGFA',	'ORICONENT',	'EMCURE',	'KMEW',	'GMDCLTD',	'SAKAR',	
'APARINDS',	'JAMNAAUTO',	'TVSHLTD',	'PFOCUS',	'ROSSTECH',	'PGIL'
]

nifty_reversal = ['STLTECH',	'MOTHERSON',	'DCBBANK']
"""
,	'BAJAJ-AUTO',	'MMFL',	'HDFCGOLD',
'SMLMAH',	'TORNTPOWER',	'ROLEXRINGS',	'ASHOKLEY',	'AJANTPHARM',	'ABCAPITAL',
'INFOBEAN',	'IDBI',	'AVANTIFEED',	'POWERGRID',	'CCL',	'BAJAJCON',
'MTARTECH',	'KRYSTAL',	'ANGELONE',	'VEDL',	'ABB',	'THELEELA',
'TDPOWERSYS',	'KIRLOSENG',	'MUFIN',	'CANTABIL',	'GRASIM',	'GROWWLIQID',
'SANSERA',	'CUPID',	'ACUTAAS',	'BHARATFORG',	'MASFIN',	'CASHIETF',
'MAHLOG',	'TATASTEEL','ABSLAMC',	'MCX',	'RMDRIP',	'GOLD1',
'TMB',	'MEDPLUS',	'GESHIP',	'VRLLOG',	'M&MFIN',	'THANGAMAYL',
'CIEINDIA',	'BANDHANBNK',	'BLISSGVS',	'BALKRISIND',	'MANAPPURAM',	'STYLEBAAZA',
'BSE',	'JKTYRE',	'NAZARA',	'SHYAMMETL',	'INDUSTOWER',
'FORCEMOT',	'MIDHANI',	'SHRINGARMS',	'MARICO',	'AKUMS',	
'GRAPHITE',	'ASTRAL',	'JBCHEPHARM',	'PETRONET',	'GOLDIETF',	
'SEAMECLTD',	'JINDALSAW',	'ONGC',	'IOC',	'DELHIVERY',	
'BSOFT',	'SGMART',	'TORNTPHARM',	'AXISBANK',	'ICICIB22',	
'CONSOFINVT',	'MBAPL',	'INDIACEM',	'RNBDENIMS',	'GOLDBETA',
'HINDCOPPER', 'BANKINDIA', 'OIL', 'HINDALCO', 
'HINDZINC', 'BSE', 'TATASTEEL', 'NATIONALUM']
"""

#nifty_test = ['KOTAKBANK','MARUTI','TVSMOTOR','SRF','SOLARINDS','NESTLEIND','DRREDDY','NAZARA','HINDALCO','IIFL','SBIN',
#'DABUR','ICICIBANK','INDUSTOWER','NYKAA', 'NHPC','OFSS','PATANJALI','PETRONET','PIIND','SAIL', 'VOLTAS','BOSCHLTD','TORNTPOWER',
#'ABB', 'BHARATFORG', 'BALKRISIND', 'VTL', 'TIMKEN', 'GVT&D', 'AARTIIND', 'APARINDS', 'NAVINFLUOR', 'SONACOMS']

sectors = ['NIFTY AUTO','NIFTY BANK','NIFTY CONSUMER DURABLES','NIFTY FINANCIAL SERVICES','NIFTY FMCG',
        'NIFTY HEALTHCARE','NIFTY IT','NIFTY METAL','NIFTY OIL & GAS','NIFTY PHARMA','NIFTY PRIVATE BANK','NIFTY PSU BANK']

nifty_50 = [
    'ADANIENT', 'ADANIPORTS', 'APOLLOHOSP', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BHARTIARTL', 'BPCL', 'BRITANNIA', 'CIPLA',
    'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK',
    'INDUSINDBK', 'INFY', 'ITC', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NESTLEIND', 'NTPC', 'ONGC', 'POWERGRID',
    'RELIANCE', 'SBILIFE', 'SBIN', 'SUNPHARMA', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TCS', 'TECHM', 'TITAN', 'ULTRACEMCO', 'WIPRO'
]

nifty_next_50 = [
    'ABB', 'ADANIENSOL', 'ADANIGREEN', 'ADANIPOWER', 'AMBUJACEM', 'APOLLOTYRE', 'ASHOKLEY', 'ATGL', 'AUROPHARMA', 'BAJAJHLDNG', 'BANDHANBNK', 'BANKBARODA',
    'BEL', 'BHARATFORG', 'BOSCHLTD', 'CANBK', 'CGPOWER', 'CHOLAFIN', 'COLPAL', 'CONCOR', 'CUMMINSIND', 'DABUR',
    'DLF', 'GAIL', 'GODREJCP', 'HAVELLS', 'HDFCAMC', 'HINDPETRO', 'ICICIGI', 'ICICIPRULI', 'IGL', 'INDIGO', 'JINDALSTEL', 'JUBLFOOD',
    'LTF', 'LICI', 'LTIM', 'MARICO', 'NAUKRI', 'NHPC', 'NMDC', 'OFSS', 'PAGEIND', 'PIDILITIND', 'PNB', 'RECLTD'
]
nifty100 = nifty_50 + nifty_next_50

top_30_fno_swing = [
    'APLAPOLLO', 'ASTRAL', 'BHARATFORG', 'BLUESTARCO', 'COFORGE', 'COLPAL', 'CUMMINSIND', 'DABUR', 'DIXON', 'PIDILITIND',
    'DIVISLAB', 'GODREJPROP', 'HDFCAMC', 'ICICIPRULI', 'KPITTECH', 'LTIM', 'LUPIN', 'MARICO', 'OFSS', 'SIEMENS',
    'PAGEIND', 'PERSISTENT', 'POLYCAB', 'SRF', 'SUPREMEIND', 'TATAELXSI', 'TORNTPOWER', 'TRENT', 'TATACOMM','SOLARINDS']
            


nifty_fno = ['360ONE', 'AARTIIND', 'ABB', 'ABCAPITAL', 'ABFRL', 'ACC', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ALKEM', 'AMBER', 'AMBUJACEM', 'ANGELONE', 
                  'APLAPOLLO', 'APOLLOHOSP', 'ASHOKLEY', 'ASIANPAINT', 'ASTRAL', 'ATGL', 'AUBANK', 'AUROPHARMA', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 
                  'BALKRISIND', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'BDL', 'BEL', 'BHARATFORG', 'BHARTIARTL', 'BHEL', 'BIOCON', 'BLUESTARCO', 
                  'BOSCHLTD', 'BPCL', 'BRITANNIA', 'BSE', 'BSOFT', 'CAMS', 'CANBK', 'CDSL', 'CESC', 'CGPOWER', 'CHAMBLFERT', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'COFORGE', 
                  'COLPAL', 'CONCOR', 'CROMPTON', 'CUMMINSIND', 'CYIENT', 'DABUR', 'DALBHARAT', 'DELHIVERY', 'DIVISLAB', 'DIXON', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT', 
                  'ETERNAL', 'EXIDEIND', 'FEDERALBNK', 'FORTIS', 'GAIL', 'GLENMARK', 'GMRAIRPORT', 'GODREJCP', 'GODREJPROP', 'GRANULES', 'GRASIM', 'HAL', 'HAVELLS', 
                  'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HFCL', 'HINDALCO', 'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HUDCO', 'ICICIBANK', 
                  'ICICIGI', 'ICICIPRULI', 'IDEA', 'IDFCFIRSTB', 'IEX', 'IGL', 'IIFL', 'INDHOTEL', 'INDIANB', 'INDIGO', 'INDUSINDBK', 'INDUSTOWER', 'INFY', 'INOXWIND', 'IOC', 
                  'IRB', 'IRCTC', 'IREDA', 'IRFC', 'ITC', 'JINDALSTEL', 'JIOFIN', 'JSL', 'JSWENERGY', 'JSWSTEEL', 'JUBLFOOD', 'KALYANKJIL', 'KAYNES', 'KEI', 'KFINTECH', 
                  'KOTAKBANK', 'KPITTECH', 'LAURUSLABS', 'LICHSGFIN', 'LICI', 'LODHA', 'LT', 'LTF', 'LTIM', 'LUPIN', 'M&M', 'M&MFIN', 'MANAPPURAM', 'MANKIND', 'MARICO', 
                  'MARUTI', 'MAXHEALTH', 'MAZDOCK', 'MCX', 'MFSL', 'MGL',  'MOTHERSON', 'MPHASIS', 'MUTHOOTFIN', 'NATIONALUM', 'NAUKRI', 'NBCC', 'NCC', 'NESTLEIND', 
                  'NHPC',  'NMDC', 'NTPC', 'NYKAA', 'OBEROIRLTY', 'OFSS', 'OIL', 'ONGC', 'PAGEIND', 'PATANJALI', 'PAYTM', 'PERSISTENT', 'PETRONET', 
                  'PFC', 'PGEL', 'PHOENIXLTD', 'PIDILITIND', 'PIIND', 'PNB', 'PNBHOUSING', 'POLICYBZR', 'POLYCAB', 'POONAWALLA', 'POWERGRID', 'PPLPHARMA', 'PRESTIGE', 'RBLBANK', 
                  'RECLTD', 'RELIANCE', 'RVNL', 'SAIL', 'SBICARD', 'SBILIFE', 'SBIN', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SJVN', 'SOLARINDS', 'SONACOMS', 
                  'SRF', 'SUNPHARMA', 'SUPREMEIND', 'SYNGENE', 'TATACHEM', 'TATACOMM', 'TATACONSUM', 'TATAELXSI', 'TATAPOWER', 'TATASTEEL', 'TATATECH', 
                  'TCS', 'TECHM', 'TIINDIA', 'TITAGARH', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TVSMOTOR', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'UNOMINDA', 'UPL', 
                  'VBL', 'VEDL', 'VOLTAS', 'WIPRO', 'YESBANK', 'ZYDUSLIFE']

#------------------------------------------------
nifty_auto = ['ASHOKLEY', 'MOTHERSON', 'BAJAJ-AUTO', 'BHARATFORG', 'TMPV', 'TIINDIA', 'MARUTI', 'BOSCHLTD', 'UNOMINDA', 'EICHERMOT', 'M&M', 
'SONACOMS', 'EXIDEIND', 'HEROMOTOCO', 'TVSMOTOR']
nifty_auto_index_movers = ['M&M', 'MARUTI', 'EICHERMOT', 'BAJAJ-AUTO', 'TVSMOTOR']
#------------------------------------------------


#------------------------------------------------
nifty_fin_services = ['360ONE', 'ABCAPITAL', 'ANGELONE', 'AXISBANK', 'BAJAJFINSV', 'BAJFINANCE', 'BSE', 'CAMS', 'CDSL', 'CHOLAFIN', 'HDFCAMC', 
'HDFCBANK', 'HDFCLIFE', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'IEX', 'IRFC', 'JIOFIN', 'KOTAKBANK', 'LICHSGFIN', 'LICI', 'LTF', 'MCX', 'MFSL', 
'MUTHOOTFIN', 'PAYTM', 'PFC', 'PNBHOUSING', 'POLICYBZR', 'RECLTD', 'SBICARD', 'SBILIFE', 'SBIN', 'SHRIRAMFIN']
nifty_fin_services_movers = ['BAJFINANCE','SHRIRAMFIN','SBILIFE','BAJAJFINSV']
#------------------------------------------------

#------------------------------------------------
nifty_fmcg = ['EMAMILTD', 'TATACONSUM', 'MARICO', 'NESTLEIND', 'HINDUNILVR', 'DABUR', 'BRITANNIA', 'GODREJCP', 'VBL', 'UNITDSPR', 'UBL', 'ITC', 
'COLPAL', 'PATANJALI', 'RADICO']
nifty_fmcg_movers = ['HINDUNILVR','ITC','BRITANNIA','NESTLEIND','TATACONSUM']
#------------------------------------------------

#------------------------------------------------
nifty_it_n_telecom = ['COFORGE', 'TECHM', 'LTIM', 'INFY', 'TCS', 'WIPRO', 'PERSISTENT', 'OFSS', 'HCLTECH', 'MPHASIS', 'AFFLE', 'BHARTIHEXA', 
'BSOFT', 'COFORGE', 'CYIENT', 'HEXT', 'HFCL', 'IDEA', 'INDUSTOWER', 'INTELLECT', 'KPITTECH', 'LTTS', 'MPHASIS', 'SONATSOFTW', 'TATACOMM', 
'TATAELXSI', 'TATATECH', 'ZENSARTECH']
nifty_it_n_telecom_movers = ['INFY','TCS','WIPRO','HCLTECH','TECHM']
#------------------------------------------------

#------------------------------------------------
#nifty_media = ['NAZARA', 'SAREGAMA', 'PVRINOX', 'TIPSMUSIC', 'DBCORP', 'ZEEL', 'SUNTV', 'HATHWAY', 'NETWORK18', 'PFOCUS']
#nifty_media_movers = ['PVRINOX','ZEEL','SUNTV', 'NAZARA', 'SAREGAMA', 'NETWORK18']
#------------------------------------------------

#------------------------------------------------
nifty_metal = ['HINDCOPPER', 'WELCORP', 'TATASTEEL', 'SAIL', 'LLOYDSME', 'JSL', 'JINDALSTEL', 'JSWSTEEL', 'APLAPOLLO', 'HINDALCO', 'ADANIENT', 
'VEDL', 'NATIONALUM', 'NMDC', 'HINDZINC']
nifty_metal_movers = ['TATASTEEL','JSWSTEEL','HINDALCO','JINDALSTEL', 'ADANIENT']
#------------------------------------------------

#------------------------------------------------
nifty_pharma_n_healthcare = ['ABBOTINDIA', 'AGARWALEYE', 'AJANTPHARM', 'ALKEM', 'APLLTD', 'APOLLOHOSP', 'ASTERDM', 'ASTRAZEN', 'AUROPHARMA', 
'BIOCON', 'CAPLIPOINT', 'CIPLA', 'COHANCE', 'CONCORDBIO', 'DIVISLAB', 'DRREDDY', 'EMCURE', 'ERIS', 'FORTIS', 'GLAND', 'GLAXO', 'GLENMARK', 
'GRANULES', 'INDGN', 'IPCALAB', 'JBCHEPHARM', 'JUBLPHARMA', 'KIMS', 'LALPATHLAB', 'LAURUSLABS', 'LUPIN', 'MANKIND', 'MAXHEALTH', 'MEDANTA', 
'METROPOLIS', 'NATCOPHARM', 'NEULANDLAB', 'NH', 'ONESOURCE', 'PFIZER', 'POLYMED', 'PPLPHARMA', 'RAINBOW', 'SAILIFE', 'SUNPHARMA', 'SYNGENE', 
'TORNTPHARM', 'VIJAYA', 'WOCKPHARMA', 'ZYDUSLIFE']
nifty_pharma_n_healthcare_movers = ['SUNPHARMA', 'CIPLA', 'DIVISLAB', 'DRREDDY', 'LUPIN', 'MAXHEALTH', 'APOLLOHOSP']
#------------------------------------------------


#------------------------------------------------
nifty_psu_banks = ['MAHABANK', 'INDIANB', 'CANBK', 'BANKINDIA', 'PNB', 'SBIN', 'BANKBARODA', 'IOB', 'UCOBANK', 'PSB', 'CENTRALBK', 'UNIONBANK']
nifty_private_banks = ['BANDHANBNK', 'RBLBANK', 'FEDERALBNK', 'AXISBANK', 'HDFCBANK', 'KOTAKBANK', 'ICICIBANK', 'IDFCFIRSTB', 'YESBANK', 'INDUSINDBK']
nifty_banks_index_movers = ['HDFCBANK', 'ICICIBANK', 'KOTAKBANK', 'AXISBANK', 'SBIN']
#------------------------------------------------

#------------------------------------------------
nifty_realty = ['PHOENIXLTD', 'GODREJPROP', 'SIGNATURE', 'OBEROIRLTY', 'LODHA', 'BRIGADE', 'SOBHA', 'DLF', 'PRESTIGE', 'ANANTRAJ']
nifty_realty_movers = ['DLF','GODREJPROP','PRESTIGE','PHOENIXLTD','LODHA']
#------------------------------------------------

#------------------------------------------------
nifty_cons_durables = ['CENTURYPLY', 'VGUARD', 'WHIRLPOOL', 'TITAN', 'VOLTAS', 'HAVELLS', 'CROMPTON', 'CERA', 'BATAINDIA', 'KAJARIACER', 'KALYANKJIL', 
'PGEL', 'BLUESTARCO', 'AMBER', 'DIXON']
nifty_cons_durables_movers = ['TITAN','VOLTAS','HAVELLS','DIXON','CROMPTON']
#------------------------------------------------

#------------------------------------------------
nifty_oil_n_gas = ['HINDPETRO', 'BPCL', 'IOC', 'OIL', 'IGL', 'ONGC', 'GAIL', 'RELIANCE', 'ATGL', 'AEGISLOG', 'GUJGASLTD', 'PETRONET', 'MGL', 'GSPL', 
'CASTROLIND']
nifty_oil_n_gas_movers = ['RELIANCE','IOC','BPCL','ONGC','GAIL']
#------------------------------------------------

#------------------------------------------------
nifty_chemicals = ['SWANCORP', 'ATUL', 'NAVINFLUOR', 'SUMICHEM', 'COROMANDEL', 'FLUOROCHEM', 'CHAMBLFERT', 'LINDEINDIA', 'PIIND', 'PIDILITIND', 'HSCL', 
'UPL', 'TATACHEM', 'BAYERCROP', 'DEEPAKNTR', 'AARTIIND', 'SOLARINDS', 'SRF', 'DEEPAKFERT', 'PCBL']
nifty_chemicals_movers = ['PIDILITIND','UPL','SRF','COROMANDEL','PIIND','SOLARINDS']
#------------------------------------------------

core_swing_midcaps = ['APLAPOLLO', 'AUBANK', 'ABBOTINDIA', 'AJANTPHARM', 'ALKEM',
    'APARINDS', 'ASTRAL', 'BSE', 'BERGEPAINT', 'BHARATFORG', 'BLUESTARCO', 'COFORGE', 'COLPAL', 'CONCOR', 'COROMANDEL',
    'CUMMINSIND', 'DABUR', 'DEEPAKNTR', 'DIXON', 'ENDURANCE', 'ESCORTS', 'EXIDEIND', 'FEDERALBNK', 'GLAXO', 'GODFRYPHLP',
    'GODREJPROP', 'FLUOROCHEM', 'GUJGASLTD', 'HDFCAMC', 'ICICIPRULI', 'IGL', 'INDUSTOWER', 'IPCALAB', 'JKCEMENT',
    'KPRMILL', 'KEI', 'KPITTECH', 'LTTS', 'LINDEINDIA', 'LUPIN', 'MANKIND', 'MARICO', 'MFSL', 'MOTILALOFS',
    'MPHASIS', 'MUTHOOTFIN', 'NAM-INDIA', 'OBEROIRLTY', 'OFSS', 'PIIND', 'PAGEIND', 'PERSISTENT', 'PETRONET',
    'PHOENIXLTD', 'POLYCAB', 'PRESTIGE', 'PGHH', 'SBICARD', 'SRF', 'SCHAEFFLER', 'SONACOMS', 'SUNDARMFIN',
    'SUPREMEIND', 'SYNGENE', 'TATACOMM', 'TATAELXSI', 'TATATECH', 'THERMAX', 'TORNTPOWER', 'TIINDIA',
    'UNOMINDA', 'UPL', 'UBL', 'VOLTAS']

core_swing_smallcaps = ['AARTIIND', 'AFFLE', 'ALKYLAMINE', 'AMBER', 'ANGELONE', 'APLLTD',
    'ASTRAZEN', 'ATUL', 'BATAINDIA', 'BLUEDART', 'CAMS', 'CDSL',
    'CERA', 'CYIENT', 'DATAPATTNS',  'DCMSHRIRAM', 'ECLERX', 'INDIAMART',
    'INTELLECT', 'KAYNES', 'LALPATHLAB', 'LATENTVIEW', 'NAVINFLUOR', 'POLYMED',
    'TITAGARH']


monopoly_stocks = ["IRCTC", "CDSL", "MCX", "IEX", "HAL", "COALINDIA", "HINDZINC", "NAUKRI", "CONCOR",
    "POWERGRID", "NTPC", "GAIL", "PETRONET", "INDUSTOWER", "SBICARD", "SBILIFE", "HDFCLIFE", "ICICIPRULI"]

duopoly_stocks = ["NESTLEIND", "PIDILITIND", "PAGEIND", "ASIANPAINT", "BERGEPAINT", "ULTRACEMCO", "AMBUJACEM", "ACC", 
    "TITAN", "MARICO", "COLPAL", "HINDUNILVR", "ITC", "BRITANNIA", "BHARTIARTL", "RELIANCE", "POLYCAB", "APLAPOLLO", 
    "DIXON","LTTS", "TATAELXSI", "OFSS"]

mono_duopoly_stocks = monopoly_stocks + duopoly_stocks
nifty_mid_small_caps = core_swing_midcaps + core_swing_smallcaps
nifty_sectoral = nifty_auto + nifty_fin_services + nifty_fmcg + nifty_it_n_telecom + \
    nifty_metal + nifty_pharma_n_healthcare + nifty_psu_banks + nifty_private_banks + \
    nifty_cons_durables + nifty_oil_n_gas + nifty_chemicals

nifty_movers = nifty_banks_index_movers + nifty_auto_index_movers + nifty_chemicals_movers + \
    nifty_fin_services_movers + nifty_fmcg_movers + nifty_pharma_n_healthcare_movers + \
    nifty_metal_movers + nifty_cons_durables_movers + nifty_oil_n_gas_movers


nifty_cash_list = ['CUPID', 'AEGISLOG', 'ATGL', 'BPCL', 'CASTROLIND', 'GAIL', 'GSPL', 'GUJGASLTD', 'HINDPETRO', 'IGL', 'IOC', 'MGL', 'OIL', 'ONGC', 'PETRONET', 
                   'RELIANCE', 'ASHOKLEY', 'BAJAJ-AUTO', 'BALKRISIND', 'BHARATFORG', 'BOSCHLTD', 'EICHERMOT', 'EXIDEIND', 'HEROMOTOCO', 'M&M', 'MARUTI', 'MOTHERSON', 
                   'MRF', 'TATAMOTORS', 'TIINDIA', 'TVSMOTOR', 'ADANIENSOL', 'ADANIGREEN', 'ADANIPOWER', 'AMBUJACEM', 'COALINDIA', 'GRASIM', 'JSWENERGY', 'NHPC', 
                   'NTPC', 'PIDILITIND', 'PIIND', 'SHREECEM', 'SRF', 'TATAPOWER', 'TORNTPOWER', 'ULTRACEMCO', 'UPL', 'AMBER', 'BATAINDIA', 'BLUESTARCO', 'CENTURYPLY', 
                   'CERA', 'CROMPTON', 'DIXON', 'HAVELLS', 'KAJARIACER', 'KALYANKJIL', 'PGEL', 'TITAN', 'VGUARD', 'VOLTAS', 'WHIRLPOOL', 'AXISBANK', 'BAJAJFINSV', 
                   'BAJFINANCE', 'CHOLAFIN', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'JIOFIN', 'KOTAKBANK', 'LICHSGFIN', 'MUTHOOTFIN', 
                   'PFC', 'RECLTD', 'SBICARD', 'SBILIFE', 'SBIN', 'SHRIRAMFIN', 'BRITANNIA', 'COLPAL', 'DABUR', 'EMAMILTD', 'GODREJCP', 'HINDUNILVR', 'ITC', 'MARICO', 
                   'NESTLEIND', 'PATANJALI', 'RADICO', 'TATACONSUM', 'UBL', 'UNITDSPR', 'VBL', 'COFORGE', 'HCLTECH', 'INFY', 'LTIM', 'MPHASIS', 'OFSS', 'PERSISTENT', 
                   'TCS', 'TECHM', 'WIPRO', 'DBCORP', 'HATHWAY', 'NAZARA', 'NETWORK18', 'PVRINOX', 'SAREGAMA', 'SUNTV', 'TIPSMUSIC', 'ZEEL', 'ADANIENT', 'APLAPOLLO', 
                   'HINDALCO', 'HINDCOPPER', 'HINDZINC', 'JINDALSTEL', 'JSL', 'JSWSTEEL', 'LLOYDSME', 'NATIONALUM', 'NMDC', 'SAIL', 'TATASTEEL', 'VEDL', 'WELCORP', 
                   'ABBOTINDIA', 'AJANTPHARM', 'ALKEM', 'AUROPHARMA', 'BIOCON', 'CIPLA', 'DIVISLAB', 'DRREDDY', 'GLAND', 'GLENMARK', 'GRANULES', 'IPCALAB', 'JBCHEPHARM', 
                   'LAURUSLABS', 'LUPIN', 'MANKIND', 'NATCOPHARM', 'SUNPHARMA', 'TORNTPHARM', 'ZYDUSLIFE', 'BANDHANBNK', 'FEDERALBNK', 'IDFCFIRSTB', 'INDUSINDBK', 
                   'RBLBANK', 'YESBANK', 'BANKBARODA', 'BANKINDIA', 'CANBK', 'CENTRALBK', 'INDIANB', 'IOB', 'MAHABANK', 'PNB', 'PSB', 'UCOBANK', 'UNIONBANK', 'ANANTRAJ', 
                   'BRIGADE', 'DLF', 'GODREJPROP', 'LODHA', 'OBEROIRLTY', 'PHOENIXLTD', 'PRESTIGE', 'RAYMOND', 'RAYMONDREL', 'SOBHA', 'A2ZINFRA', 'AAKASH', 'ACCURACY', 
                   'ACESTONE', 'AFIL', 'AGSTRA', 'AJOONI', 'AKG', 'AKI', 'AKSHOPTFBR', 'ALANKIT', 'ALMONDZ', 'ALOKINDS', 'AMARKANTAK', 'AMARVAN', 'ANKITMETAL', 'ANMOL', 
                   'ANSALAPI', 'ANTGRAPHIC', 'AONETOTAL', 'ARCHIES', 'ARSHIYA', 'ASHOKAMET', 'ASMS', 'ASTRON', 'ATALREAL', 'AVONMORE', 'AXITA', 'BAGFILMS', 'BAIDFIN', 
                   'BAJAJHIND', 'BALKRISHNA', 'BHANDARI', 'BINANIIND', 'BLBLIMITED', 'BRNL', 'BTML', 'CALSOFT', 'CAPFIN', 'CAPTRU-RE', 'CCCL', 'CCHHL', 'CELEBRITY', 
                   'CENTEXT', 'CEREBRAINT', 'CINEVISTA', 'CITYGOLD', 'COMPINFO', 'COMPUSOFT', 'CONSUMER', 'COUNCODOS', 'CRED', 'CYBERMEDIA', 'DANGEE', 'DAVANGERE', 
                   'DCMFINSERV', 'DENIMDL', 'DEVRUPTRAD', 'DEWANHOUS', 'DIGISPICE', 'DIL', 'DISHTV', 'DNAMEDIA', 'DPSCLTD', 'DRCSYSTEMS', 'DUCON', 'EBSL', 'ECAPINSURE', 
                   'EIFL', 'ENERGYDEV', 'EQUAL200', 'EQUIPPP', 'ESSENTIA', 'EUROTEXIND', 'EXXARO', 'FCSSOFT', 'FELDVR', 'FIRL', 'FLFL', 'FMNL', 'FRICKINDIA', 'FSC', 
                   'GANGAFORGE', 'GATECH', 'GATECHDVR', 'GAYAHWS', 'GAYAPROJ', 'GDHL', 'GENUSPAPER', 'GLFL', 'GLOBALE', 'GLOBE', 'GOLDCASE', 'GOYALALUM', 'GRACIOUS', 
                   'GREENPOWER', 'GROWWMOM50', 'GROWWN200', 'GTECJAINX', 'GTL', 'GTLINFRA', 'GVKPIL', 'HARDWYN', 'HAVISHA', 'HCL-INSYS', 'HDFCLOWVOL', 'HDFCMID150', 
                   'HEADSUP', 'HEALTHY', 'HILLRIDGE', 'HLVLTD', 'HOTAHOTI', 'HTMEDIA', 'HYBRIDFIN', 'IDEA', 'IEL', 'IIEL', 'IL&FSTRANS', 'IMPEXFERRO', 'INDOWIND', 
                   'INDSWFTLTD', 'INDUENG', 'INFIBEAM', 'INVENTURE', 'IVC', 'JECOEXP', 'JHS', 'JOTINDRA', 'JPPOWER', 'JYOTISTRUC', 'KABIRDAS', 'KAMINI', 'KANANIIND', 
                   'KEEPLEARN', 'KESORAMIND', 'KHANDSE', 'KRIDHANINF', 'KSHITIJPOL', 'LAFFANSOFT', 'LAKPRE', 'LAL', 'LANCORHOL', 'LASA', 'LATTEYS', 'LIBAS', 'LOGICINFO', 
                   'LOWVOL1', 'LPDC', 'LYPSAGEMS', 'MADHUCON', 'MAHKTECH', 'MANUGRAPH', 'MAXPLUS', 'MEP', 'METAL', 'MGEL', 'MGLFL', 'MID150', 'MIRCELECTR', 'MITTAL', 'MKPL', 
                   'MOKSH', 'MOLIND', 'MONIFTY500', 'MOSMALL250', 'MOTISONS', 'MTEDUCARE', 'MULTICAP', 'NAGAFERT', 'NANDINI', 'NARMADA', 'NAVKARURB', 'NAWRATAN', 'NCCL', 
                   'NDL', 'NECCLTD', 'NECLIFE', 'NEPACL', 'NEWAGE', 'NEWERA', 'NEXTMEDIA', 'NIFTYQLITY', 'NILAINFRA', 'NILASPACES', 'NKTEXTILE', 'NOIDATOLL', 'ONELIFECAP', 
                   'ORCHASP', 'ORIENTALTL', 'ORTINGLOBE', 'OSIAHYPER', 'OSWALMIN', 'OSWALSEEDS', 'PARASPETRO', 'PARSVNATH', 'PATINTLOG', 'PCJEWELLER', 'PHARMABEES', 'PILITA', 
                   'PILLAR', 'PKLEASING', 'PRAENG', 'PRAKASHSTL', 'PRAXIS', 'PREMIER', 'PRHOLDING', 'PRITIKAUTO', 'PRIYAINT', 'PURBANCHAL', 'PVP', 'RADAAN', 'RADIOCITY', 'RAJMET', 
                   'RAMASTEEL', 'RANASUG', 'REGALENTER', 'RHFL', 'RITZ', 'ROLLT', 'RTNPOWER', 'RUCHINFRA', 'SAANVI', 'SABEVENTS', 'SADBHAV', 'SADBHIN', 'SADHNANIQ', 'SAKHTISUG', 
                   'SAKUMA', 'SALASAR', 'SALSTEEL', 'SAMBHAAV', 'SAMYAK', 'SANCO', 'SARVESHWAR', 'SATYASHYAM', 'SBC', 'SBHL', 'SEPC', 'SETCO', 'SGL', 'SHAH', 'SHANTI', 
                   'SHEKHAWATI', 'SHYAMCENT', 'SHYAMTEL', 'SIL', 'SILLYMONKS', 'SIMBHALS', 'SMMIL', 'SPANGLE', 'SPCENET', 'STCL', 'STEADFAST', 'STEELXIND', 'SUBEXLTD', 
                   'SUNDARAM', 'SURANAT&P', 'SUVIDHAA', 'SVPGLOB', 'SYNCOMF', 'TAKE', 'TARANGINI', 'TATAGOLD', 'TCIFINANCE', 'TECILCHEM', 'TFL', 'TGBHOTELS', 'TIJARIA', 
                   'TNTELE', 'TREEHOUSE', 'TRU', 'TTL', 'TVVISION', 'UDDHAV', 'ULL', 'UMESLTD', 'UNIINFO', 'UNITECH', 'UNITEDPOLY', 'URJA', 'UTKARSHBNK', 'UYFINCORP', 
                   'VAISHALI', 'VAKRANGEE', 'VARDMNPOLY', 'VIJIFIN', 'VIKASECO', 'VIKASLIFE', 'VINNY', 'VIPULLTD', 'VIRINCHI', 'VISHWARAJ', 'VISISTH', 'WINMORE', 'WINSOME', 
                   'XLTELENE', 'YAARI', 'ZEELEARN', 'ZEEMEDIA', 'ZENITHSTL', 'TOP10ADD', 'LOVABLE', 'CUBEXTUB', 'MOPSE', 'MAWANASUG', 'LAGNAM', 'BALPHARMA', 'NXT-INFRA', 
                   'OMAXE', 'BELRISE', 'TEXINFRA', 'SILVERBEES', 'HDFCSILVER', 'IGCL', 'SILVERADD', 'GROWWLIQID', 'SILVER1', 'ARCHIDPLY', 'ANIKINDS', 'ATAM', 'MOVALUE', 
                   'SBISILVER', 'SILVER360', 'NAVKARCORP', 'AUSOMENT', 'RAJOOENG', 'BHARATSE', 'NTPCGREEN', 'FOCUS', 'SHREMINVIT', 'GROWWSLVR', 'DONEAR', 'INSPIRISYS', 
                   'DCM', 'AXISILVER', 'STEELCITY', 'BGRENERGY', 'SEITINVIT', 'SILVER', 'ESILVER', 'EMMBI', 'AIROLAM', 'MAHAPEXLTD', 'NDRINVIT', 'AARVI', 'LIQUIDCASE', 
                   'GSEC10ABSL', 'ICICIB22', 'EMAMIREAL', 'JAICORPLTD', 'ABGSEC', 'ZODIACLOTH', 'ISFT', 'ZIMLAB', 'DJML', 'J&KBANK', 'GAEL', 'TOUCHWOOD', 'STLTECH', 
                   'SPORTKING', 'LYKALABS', 'KRITINUT', 'SBFC', 'INTERISE', 'WCIL', 'JAYSREETEA', 'EDELWEISS', 'INDUSINVIT', 'ANZEN', 'SICALLOG', 'FOODSIN', 'GSLSU', 
                   'VALIANTLAB', 'EMBDL', 'FEDFINA', 'NBCC', 'BEPL', 'DEVIT', 'SARLAPOLY', 'PIGL', 'GTPL', 'ALEMBICLTD', 'GMRP&UI', 'WEIZMANIND', 'RGL', 'BANARBEADS', 
                   'INDSWFTLAB', 'HDFCGROWTH', 'MAANALU', 'KHAITANLTD', 'CONS', 'BAJAJHFL', 'SAH', 'GARUDA', 'UNIECOM', 'MARBLE', 'ELECTCAST', 'SMLT', 'SAMMAANCAP', 'MENONBE', 
                   'SINTERCOM', 'THEMISMED', 'SPECIALITY', 'NIITLTD', 'VETO', 'KUANTUM', 'JAIBALAJI', 'GPTINFRA', 'KOKUYOCMLN', 'VMM', 'PDMJEPAPER', 'SUPREMEINF', 'NAHARINDUS', 
                   'COMSYN', 'CUBEINVIT', 'PALASHSECU', 'MODIRUBBER', 'PVSL', 'REMSONSIND', 'ESTER', 'RELTD', 'TOKYOPLAST', 'TVSSCS', 'CONSUMBEES', 'SDL26BEES', 'OCCLLTD', 
                   'OMINFRAL', 'NHIT', 'GILLANDERS', 'RAMAPHO', 'RPPINFRA', 'ATLASCYCLE', 'HDFCVALUE', 'VINCOFE', 'LAMBODHARA', 'HEMIPROP', 'SURYODAY', 'KALYANI', 
                   'KELLTONTEC', 'LEMONTREE', 'MASTERTR', 'IRFC', 'MUNJALSHOW', 'MANAKCOAT', 'DBEIL', 'BROOKS', 'REDTAPE', 'KECL', 'NELCAST', 'EKC', 'BSHSL', 'RBZJEWEL', 
                   'JTEKTINDIA', 'DCBBANK', 'MAHEPC', 'NAVNETEDUL', 'MANBA', 'NXST', 'SHEMAROO', 'SERVOTECH', 'WELSPUNLIV', 'WORTH', 'STCINDIA', 'ORIENTHOT', 'SOUTHWEST', 
                   'MUKANDLTD', 'RUCHIRA', 'DIACABS', 'AFDIL', 'MOMGF', 'MRPL', 'RAIN', 'LINC', 'EMIL', 'HEALTHADD', 'MAKEINDIA', 'THEINVEST', 'ENIL', 'BEDMUTHA', 'APCL', 
                   'NV20', 'NV20BEES', 'HPIL', 'INDOUS', 'NDTV', 'MAFANG', 'MUTHOOTMF', 'SMCGLOBAL', 'APTECHT', 'RATNAVEER', 'NITCO', 'INOXGREEN', 'AARVEEDEN', 'BANSWRAS', 
                   'RCF', 'UNIENTER', 'AHLEAST', 'INDIGRID', 'SDBL', 'AGRITECH', 'UCAL', 'SECMARK', 'PROSTARM', 'HECPROJECT', 'PARKHOTELS', 'DHAMPURSUG', 'SPARC', 'THOMASCOOK', 
                   'GPPL', 'SMARTLINK', 'KALAMANDIR', 'SOMICONVEY', 'PRSMJOHNSN', 'PRAKASH', 'PARADEEP', 'GPTHEALTH', 'HIMATSEIDE', 'WEL', 'AVANTEL', 'BOROSCI', 'CPCAP', 
                   'LORDSCHLO', 'PFOCUS', 'BBTCL', 'VPRPL', 'KAKATCEM', 'BLISSGVS', 'DALMIARF', 'WIPL', 'ABLBL', 'JOCIL', 'MANOMAY', 'ARISINFRA', 'BOMDYEING', 'CYBERTECH', 
                   'MOLDTECH', 'KRITI', 'CGCL', 'MODISONLTD', 'MUFTI', 'TIMESGTY', 'SATIN', 'MASKINVEST', 'JMFINANCIL', 'IREDA', 'SGLTL', 'TOLINS', 'INDOAMIN', 'IITL', 
                   'HINDOILEXP', 'GANGESSECU', 'AVROIND', 'ABINFRA', 'TEXRAIL', 'GULPOLY', 'MIDCAP', 'GANDHAR', 'IXIGO', 'TVTODAY', 'DCMSRIND', 'DEVYANI', 'REPL', 'ELIN', 
                   'MOSCHIP', 'PYRAMID', 'VRAJ', 'INOXWIND', 'SHAREINDIA', 'CURAA', 'SUPERHOUSE', 'RKSWAMY', 'HDFCSML250', 'RELCHEMQ', 'DCMNVL', 'RSWM', 'CROWN', 'DREAMFOLKS', 
                   'BIRLACABLE', 'KOTHARIPET', 'INDOFARM', 'ADSL', 'CESC', 'PTC', 'KOPRAN', 'SUKHJITS', 'RAMARAJU', 'GPIL', 'HEXATRADEX', 'BSL', 'SEQUENT', 'STARPAPER', 
                   'UGROCAP', 'PRECWIRE', 'TNPL', 'APOLLO', 'TARC', 'SHALBY', 'VSTL', 'NIACL', 'EXICOM', 'ARVEE', 'FUSION', 'MANINFRA', 'MAXIND', 'BLSE', 'MON100', 'KROSS', 
                   'KTKBANK', 'IVP', 'BIRLAMONEY', 'MANCREDIT', 'AURUM', 'LXCHEM', 'IRCON', 'CORDSCABLE', 'GICHSGFIN', 'NOCIL', 'SCODATUBES', 'DTIL', 'AEROFLEX', 'MOQUALITY', 
                   'TBZ', 'CHEMCON', 'IEX', 'HISARMETAL', 'NYKAA', 'KRONOX', 'KCP', 'PPLPHARMA', 'RAJESHEXPO', 'HERCULES', 'NITIRAJ', 'SHIVATEX', 'BHAGERIA', 'ARKADE', 
                   'FINPIPE', 'KANPRPLA', 'ASHOKA', 'ZUARI', 'GSFC', 'LOWVOL', 'MARINE', 'LTF', 'PRECAM', 'BHARATWIRE', 'CONSOFINVT', 'HITECHCORP', 'IPL', 'PAKKA', 'STARCEMENT', 
                   'HEIDELBERG', 'BALMLAWRIE', 'BLAL', 'ORBTEXP', 'LFIC', 'GIPCL', 'TAINWALCHM', 'PLASTIBLEN', 'IKIO', 'DELPHIFX', 'WALCHANNAG', 'ANUHPHR', 'RUPA', 'ITCHOTELS', 
                   'NATCAPSUQ', 'CUB', 'RELIGARE', 'IRBIT', 'SAMHI', 'NIFMID150', 'INDOBORAX', 'BORANA', 'KNRCON', 'HARRMALAYA', 'ORIENTELEC', 'MVGJL', 'NATHBIOGEN', 'NCC', 
                   'PENIND', '20MICRONS', 'NLCINDIA', 'MHLXMIRU', 'CHEMBOND', 'MID150BEES', 'MINDTECK', 'SAKSOFT', 'SBIETFQLTY', 'HUDCO', 'PANACHE', 'SCHAND', 'SCI', 'DIGITIDE', 
                   'SIGNPOST', 'UNIDT', 'EPL', 'JAGSNPHARM', 'PARAGMILK', 'HUHTAMAKI', 'NCLIND', 'JINDALSAW', 'EIEL', 'LOKESHMACH', 'PPAP', 'BAJAJCON', 'OCCL', 'VERANDA', 
                   'KAMATHOTEL', 'SHK', 'DBREALTY', 'ORIENTCEM', 'VAIBHAVGBL', 'AYMSYNTEX', 'RACE', 'SHREYANIND', 'ENGINERSIN', 'SPMLINFRA', 'TREJHARA', 'RESPONIND', 'UNIVASTU', 
                   'MOBIKWIK', 'SMSPHARMA', 'BAJEL', 'APEX', 'WAAREEINDO', 'GREENLAM', 'AUTOBEES', 'SSWL', 'DPWIRES', 'ZENITHEXPO', 'EMKAY', 'AMNPLST', 'KAPSTON', 'NORTHARC', 
                   'SREEL', 'AEGISVOPAK', 'KANSAINER', 'RUBYMILLS', 'NACLIND', 'GODAVARIB', 'SAGCEM', 'ARTEMISMED', 'KHADIM', 'DAMCAPITAL', 'VSSL', 'ACMESOLAR', 'SALONA', 'PANSARI', 
                   'AFSL', 'VLSFINANCE', 'MIDQ50ADD', 'BHEL', 'DMCC', 'AWL', 'MARKSANS', 'LAOPALA', 'GSEC10IETF', 'SETF10GILT', 'SIMPLEXINF', 'ETERNAL', 'NIFTYBETF', 'JAYAGROGN', 
                   'GLOBALVECT', 'MOM50', 'MANGCHEFER', 'NIFTY50ADD', 'SWANDEF', 'SKMEGGPROD', 'DCAL', 'ADFFOODS', 'SUVEN', 'M&MFIN', 'DDEVPLSTIK', 'PLATIND', 'RHL', 'KARURVYSYA', 
                   'KEYFINSERV', 'WANBURY', 'SETFNIF50', 'EIFFL', 'TRANSWORLD', 'MANAPPURAM', 'FCL', 'CEIGALL', 'CAMPUS', 'DCI', 'NETF', 'NIFTYETF', 'ZUARIIND', 'NIF100BEES', 
                   'CANTABIL', 'ABCAPITAL', 'MEGASTAR', 'NAHARSPING', 'SANGHVIMOV', 'FINOPB', 'NIFTY1', 'AXISNIFTY', 'IDFNIFTYET', 'TFCILTD', 'UTINIFTETF', 'SPANDANA', 'LICNETFN50', 
                   'RITES', 'KITEX', 'CAPITALSFB', 'RISHABH', 'HDFCNIFTY', 'ALPHAGEO', 'LICNFNHGP', 'HINDWAREAP', 'HUBTOWN', 'SASTASUNDR', 'SBIETFPB', 'ASIANENE', 'NIFTYIETF', 
                   'VSTIND', 'NRBBEARING', 'NURECA', 'LOYALTEX', 'NIFTYBEES', 'ICIL', 'DENTA', 'TERASOFT', 'LIKHITHA', 'FLAIR', 'RAMCOIND', 'STYLEBAAZA', 'NPBET', 'AVG', 'MMP', 
                   'GREENPANEL', 'ASPINWALL', 'UDS', 'TIRUMALCHM', 'KIOCL', 'PRIMESECU', 'PURVA', 'UTTAMSUGAR', 'DCXINDIA', 'STARTECK', 'AKSHARCHEM', 'JUNIPER', 'UEL', 'KABRAEXTRU', 
                   'DYNPRO', 'POWERGRID', 'RITCO', 'TALBROAUTO', 'HONASA', 'RPTECH', 'ECOSMOBLTY', 'CAMLINFINE', 'BHAGCHEM', 'AGROPHOS', 'AIRAN', 'AKASH', 'ALLCARGO', 'AMBICAAGAR', 
                   'AMDIND', 'AROGRANITE', 'ASHIMASYN', 'ATL', 'ATLANTAA', 'AXISVALUE', 'BALAJEE', 'BALAXI', 'BASML', 'BCLIND', 'BEARDSELL', 'BFSI', 'BIOFILCHEM', 'BLUECOAST', 
                   'BOHRAIND', 'BSLNIFTY', 'BVCL', 'CENTRUM', 'CIFL', 'COASTCORP', 'COFFEEDAY', 'CORALFINAC', 'CTE', 'DAMODARIND', 'DBSTOCKBRO', 'DELHISAFE', 'DEN', 'DGCONTENT', 
                   'DHANBANK', 'DIGIDRIVE', 'DIGJAMLMTD', 'DWARKESH', 'EMULTIMQ', 'ESAFSFB', 'ESG', 'ESSARSHPNG', 'EVINDIA', 'FLEXITUFF', 'GENCON', 'GENSOL', 'GINNIFILA', 'GOKUL', 
                   'GOLDENTOBC', 'GROWWEV', 'GROWWRAIL', 'GSEC10YEAR', 'GSS', 'GUJRAFFIA', 'GULFPETRO', 'HARDOLI', 'HCC', 'HDFCBSE500', 'HDFCMOMENT', 'HDFCNIF100', 'HDFCNIFIT', 
                   'HDFCPVTBAN', 'HINDCON', 'HINDMOTORS', 'HMAAGRO', 'IL&FSENGG', 'INCREDIBLE', 'INDBANK', 'INDORAMA', 'INDTERRAIN', 'INTERTEC', 'ISL', 'IT', 'ITBEES', 'JAIPURKURT', 
                   'JAYNECOIND', 'JISLDVREQS', 'KAMDHENU', 'KAVDEFENCE', 'KCPSUGIND', 'KMSUGAR', 'KOHINOOR', 'KOTARISUG', 'LAXMICOT', 'LEXUS', 'LTGILTBEES', 'MADHAV', 'MALUPAPER', 
                   'MBLINFRA', 'MCLEODRUSS', 'MEDICO', 'MFML', 'MIRZAINT', 'MNC', 'MOCAPITAL', 'MODTHREAD', 'MOHEALTH', 'MOHITIND', 'MOLOWVOL', 'MOMENTUM', 'MON50EQUAL', 'MOTOGENFIN', 
                   'MSCIINDIA', 'MSPL', 'MUKKA', 'MURUDCERA', 'NAGREEKEXP', 'NEXT30ADD', 'NGIL', 'NIBL', 'NIFTY100EW', 'NORBTEAEXP', 'NOVAAGRI', 'NSLNISP', 'ODIGMA', 'OLAELEC', 
                   'ORICONENT', 'ORIENTCER', 'ORIENTPPR', 'OSWALGREEN', 'PAISALO', 'PATELENG', 'PEARLPOLY', 'PENINLAND', 'PFS', 'PIONEEREMB', 'PNC', 'PRIMO', 'PROZONER', 'PRUDMOULI', 
                   'PTL', 'PVTBANKADD', 'RAJRILTD', 'RAJSREESUG', 'RAJTV', 'RAMANEWS', 'RANJANPOLY', 'REGENCERAM', 'RENUKA', 'RETAIL', 'RKDL', 'RPPL', 'RUSHIL', 'SAGARDEEP', 'SAGILITY', 
                   'SAMPANN', 'SBGLP', 'SBIBPB', 'SELECTIPO', 'SELMC', 'SHIVAMAUTO', 'SHREERAMA', 'SMALLCAP', 'SNXT30BEES', 'SOMATEX', 'SONAMLTD', 'SOUTHBANK', 'SPLIL', 'SUNAYANA', 
                   'SURANASOL', 'SUTLEJTEX', 'TARAPUR', 'TARINIENT', 'TECH', 'TICL', 'TIRUPATIFL', 'TREL', 'TRIDENT', 'UDAICEMENT', 'UGARSUGAR', 'UJJIVANSFB', 'USK', 'VASWANI', 
                   'VINEETLAB', 'VIPCLOTHNG', 'VISASTEEL', 'VLEGOV', 'WEWIN', 'WILLAMAGOR', 'XTGLOBAL', 'PNCINFRA', 'ROTO', 'SUNFLAG', 'UNIVPHOTO', 'PRABHA', 'DIFFNKG', 'JSWINFRA', 
                   'SULA', 'ORIENTBELL', 'QUESS', 'SAHYADRI', 'SESHAPAPER', 'BARBEQUE', 'GOKULAGRO', 'SWSOLAR', 'MASFIN', 'GREENPLY', 'SCPL', 'BIRET', 'REDINGTON', 'PODDARMENT', 
                   'DEEDEV', 'SRGHFL', 'IRMENERGY', 'MUTHOOTCAP', 'RALLIS', 'GEPIL', 'MAZDA', 'EVEREADY', 'NAHARCAP', 'EQUAL50', 'INDIANCARD', 'GNA', 'VINYLINDIA', 'ONWARDTEC', 
                   'SURAKSHA', 'ITI', 'BOROLTD', 'CAPACITE', 'SKYGOLD', 'JNKINDIA', 'STANLEY', 'APTUS', 'INDOCO', 'ATHERENERG', 'EQUAL50ADD', 'SHREEPUSHK', 'DHARMAJ', 'SAPPHIRE', 
                   'NIITMTS', 'PONNIERODE', 'GODIGIT', 'CSLFINANCE', 'ASHIANA', 'MAHASTEEL', 'ADVENZYMES', 'DVL', 'TI', 'SURYAROSNI', 'SURAJEST', 'IIFLCAPS', 'HIKAL', 'GOLDIAM', 
                   'EPACK', 'INDOSTAR', 'SAKAR', 'GUFICBIO', 'BCONCEPTS', 'GUJTHEM', 'MHRIL', 'CLSEL', 'ARVIND', 'INDIACEM', 'STERTOOLS', 'ORIENTTECH', 'PANAMAPET', 'JYOTHYLAB', 
                   'ARIES', 'MAHLOG', 'KSOLVES', 'GOPAL', 'NUVOCO', 'GENUSPOWER', 'AVL', 'NAHARPOLY', 'VPL', 'MAHLIFE', 'SENCO', 'PRINCEPIPE', 'GOCLCORP', 'OAL', 'ASIANHOTNR', 
                   'MMFL', 'EIHOTEL', 'JKTYRE', 'FSL', 'NRAIL', 'TRIVENI', 'SIS', 'FIRSTCRY', 'RELINFRA', 'HERANBA', 'GEECEE', 'AARON', 'THOMASCOTT', 'USHAMART', 'S&SPOWER', 
                   'MONARCH', 'SIGMA', 'SWIGGY', 'JWL', 'BLS', 'GRMOVER', 'GICRE', 'MOIL', 'SURAJLTD', 'DOLLAR', 'INFOBEAN', 'BESTAGRO', 'TRF', 'WINDMACHIN', 'KRISHIVAL', 'CREST', 
                   'TARSONS', 'EIHAHOTELS', 'HNGSNGBEES', 'BANSALWIRE', 'ROHLTD', 'GUJAPOLLO', 'IRIS', 'RVNL', 'QUICKHEAL', 'JITFINFRA', 'PPL', 'EMBASSY', 'KRBL', 'DALMIASUG', 
                   'IGIL', 'TIL', 'NITINSPIN', 'LIBERTSHOE', 'DELHIVERY', 'RAMCOSYS', 'GMDCLTD', 'ARIHANTSUP', 'APCOTEXIND', 'JKPAPER', 'TAJGVK', 'PDSL', 'MEDICAMEQ', 'NIFITETF', 
                   'SOFTTECH', 'PCBL', 'HARSHA', 'PANACEABIO', 'SIRCA', 'THELEELA', 'INDUSTOWER', 'STEL', 'UNIPARTS', 'MINDSPACE', 'ZAGGLE', 'CSBBANK', 'RAILTEL', 'VIPIND', 'VIDHIING',
                   'RAJRATAN', 'BEL', 'MBAPL', 'SONATSOFTW', 'VALIANTORG', 'KRISHANA', 'MAMATA', 'AXISTECETF', 'PAVNAIND', 'IZMO', 'LAXMIDENTL', 'REPCOHOME', 'SBIETFIT', 'STARHEALTH', 
                   'KALPATARU', 'CHEMPLASTS', '5PAISA', 'AFCONS', 'MANINDS', 'MIDHANI', 'APOLLOPIPE', 'AGARWALEYE', 'SARDAEN', 'KAYA', 'HARIOMPIPE', 'HLEGLAS', 'KILITCH', 'DIAMINESQ', 
                   'TVSELECT', 'BLACKBUCK', 'VENUSREM', 'BSOFT', 'SOTL', 'ABDL', 'ASAHISONG', 'ASHAPURMIN', 'DEEPINDS', 'TMB', 'UNITEDTEA', 'SANGAMIND', 'LATENTVIEW', 'SUNTECK', 
                   'REFEX', 'TIMETECHNO', 'SWANENERGY', 'CIEINDIA', 'CARRARO', 'PRICOLLTD', 'RSYSTEMS', 'AADHARHFC', 'ATULAUTO', 'NINSYS', 'DOLPHIN', 'RATEGAIN', 'APOLLOTYRE', 
                   'VIMTALABS', 'INDIANHUME', 'ARVINDFASN', 'QUADFUTURE', 'SUPRAJIT', 'AARTIIND', 'POONAWALLA', 'SONACOMS', 'ROSSTECH', 'RHIM', 'SEJALLTD', 'BAJAJHCARE', 'NIPPOBATRY', 
                   'ZODIAC', 'SRM', 'KOLTEPATIL', 'SANDUMA', 'GOACARBON', 'IGPL', 'SEMAC', 'LTFOODS', 'URAVIDEF', 'IIFL', 'TDPOWERSYS', 'SKIPPER', 'TARIL', 'HEG', 'BFINVEST', 
                   'HINDCOMPOS', 'AARTIDRUGS', 'HSCL', 'CYIENTDLM', 'JSFB', 'MAXESTATES', 'SHOPERSTOP', 'KPEL', 'PRAJIND', 'VTL', 'HERITGFOOD', 'SUNDARMHLD', 'SHANTIGEAR', 
                   '21STCENMGM', 'AAATECH', 'AAREYDRUGS', 'AARTECH', 'AASHRIT', 'ABAN', 'ABFRL', 'ABMINTLLTD', 'ABSLNN50ET', 'ACL', 'ACLGATI', 'ADL', 'ADVANIHOTR', 'AEROENTER', 
                   'AHLADA', 'ALKALI', 'ALPA', 'ALPHA', 'AMJLAND', 'ANDHRAPAP', 'ANDHRSUGAR', 'ARENTERP', 'ARIHANTCAP', 'ARTNIRMAN', 'ASIANTILES', 'AUTOIND', 'AVTNPL', 'AXISGOLD', 
                   'AXSENSEX', 'BAFNAPH', 'BALAJITELE', 'BANG', 'BANKA', 'BANKPSU', 'BBNPPGOLD', 'BHAGYANGR', 'BHARATGEAR', 'BIGBLOC', 'BIUL', 'BLKASHYAP', 'BLUSPRING', 'BODALCHEM', 
                   'BPL', 'BYKE', 'CAPINVIT', 'CAPTRUST', 'CINELINE', 'CLEDUCATE', 'CONFIPET', 'DBOL', 'DCW', 'DELTACORP', 'DELTAMAGNT', 'DHANI', 'DHRUV', 'DIVOPPBEES', 'EBANKNIFTY', 
                   'EGOLD', 'ELGIRUBCO', 'EMAMIPAP', 'EQUITASBNK', 'FIBERWEB', 'FILATEX', 'GANESHBE', 'GATEWAY', 'GEEKAYWIRE', 'GEOJITFSL', 'GFLLIMITED', 'GHCLTEXTIL', 'GILT5YBEES', 
                   'GLOBAL', 'GMRAIRPORT', 'GOLD1', 'GOLD360', 'GOLDBEES', 'GOLDSHARE', 'GOLDTECH', 'GROWWDEFNC', 'GROWWGOLD', 'HDFCGOLD', 'HDFCNEXT50', 'HDFCNIFBAN', 'HDFCPSUBK', 
                   'HDFCQUAL', 'HDFCSENSEX', 'HFCL', 'HILTON', 'HMT', 'HMVL', 'HOVS', 'HPAL', 'ICDSLTD', 'IDBI', 'IFCI', 'IMAGICAA', 'INTENTECH', 'INTLCONV', 'IOLCP', 'IRBINVIT', 
                   'IRISDOREME', 'ISHANCH', 'JAGRAN', 'JAMNAAUTO', 'JAYBARMARU', 'JINDWORLD', 'JISLJALEQS', 'JMA', 'JTLIND', 'KANORICHEM', 'KARMAENG', 'KHAICHEM', 'KOTHARIPRO', 
                   'KREBSBIO', 'LICNMID100', 'LLOYDSENGG', 'LLOYDSENT', 'LOTUSEYE', 'MADRASFERT', 'MAHESHWARI', 'MANAKSIA', 'MANAKSTEEL', 'MANALIPETC', 'MANGALAM', 'MARALOVER', 
                   'MASPTOP50', 'MCL', 'MCLOUD', 'MEGASOFT', 'MICEL', 'MILIND', 'MITCON', 'MMTC', 'MODEFENCE', 'MOGSEC', 'MOINFRA', 'MOL', 'MOM100', 'MOMENTUM50', 'MOMOMENTUM', 
                   'MONEXT50', 'MONQ50', 'MOREPENLAB', 'MOTOUR', 'MSUMI', 'MTNL', 'MUFIN', 'MUKTAARTS', 'MUNJALAU', 'NDLVENTURE', 'NIRAJ', 'NIVABUPA', 'NKIND', 'NRL', 'OBCL', 
                   'OILCOUNTUB', 'OMAXAUTO', 'ONEPOINT', 'ONMOBILE', 'ORIENTLTD', 'OSWALAGRO', 'PAR', 'PARACABLES', 'PASUPTAC', 'PGINVIT', 'PLAZACABLE', 'PNBGILTS', 'PREMIERPOL', 
                   'PRITI', 'PSUBANKADD', 'PSUBNKBEES', 'QGOLDHALF', 'RADHIKAJWE', 'RADIANTCMS', 'RBA', 'RELIABLE', 'RICOAUTO', 'RKEC', 'ROML', 'ROSSELLIND', 'RPOWER', 'RSSOFTWARE', 
                   'RTNINDIA', 'RUBFILA', 'SANGHIIND', 'SANSTAR', 'SATIA', 'SAURASHCEM', 'SCILAL', 'SENSEXADD', 'SHAHALLOYS', 'SHALPAINTS', 'SHIVAMILLS', 'SHRADHA', 'SHREDIGCEM', 
                   'SHRIRAMPPS', 'SIGACHI', 'SIGIND', 'SIKKO', 'SILGO', 'SINCLAIR', 'SITAL', 'SJVN', 'SNOWMAN', 'SPENCERS', 'SPIC', 'SRD', 'SSDL', 'STALLION', 'SUMEETINDS', 'SUMIT', 
                   'SUPREME', 'SURYALAXMI', 'SUZLON', 'TARACHAND', 'TARMAT', 'TEXMOPIPES', 'TNPETRO', 'TOTAL', 'TPLPLASTEH', 'TRACXN', 'TRIGYN', 'TTML', 'UFO', 'UMAEXPORTS', 
                   'UMANGDAIRY', 'UMIYA-MRO', 'UNIONGOLD', 'UTINEXT50', 'UTISXN50', 'VASCONEQ', 'VHLTD', 'VISAKAIND', 'WSI', 'XCHANGING', 'XELPMOC', 'YATRA']