nifty_test = ['UNIONBANK','KOTAKBANK']
#nifty_test = ['KOTAKBANK','MARUTI','TVSMOTOR','SRF','SOLARINDS','NESTLEIND','DRREDDY','NAZARA','HINDALCO',
#'DABUR','ICICIBANK','INDUSTOWER','NYKAA','ABB','NHPC','OFSS','PATANJALI','PETRONET','PIIND','SAIL', 'VOLTAS','BOSCHLTD','TORNTPOWER']

nifty_fno = ['360ONE', 'AARTIIND', 'ABB', 'ABCAPITAL', 'ABFRL', 'ACC', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ALKEM', 'AMBER', 'AMBUJACEM', 'ANGELONE', 
                  'APLAPOLLO', 'APOLLOHOSP', 'ASHOKLEY', 'ASIANPAINT', 'ASTRAL', 'ATGL', 'AUBANK', 'AUROPHARMA', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 
                  'BALKRISIND', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'BDL', 'BEL', 'BHARATFORG', 'BHARTIARTL', 'BHEL', 'BIOCON', 'BLUESTARCO', 
                  'BOSCHLTD', 'BPCL', 'BRITANNIA', 'BSE', 'BSOFT', 'CAMS', 'CANBK', 'CDSL', 'CESC', 'CGPOWER', 'CHAMBLFERT', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'COFORGE', 
                  'COLPAL', 'CONCOR', 'CROMPTON', 'CUMMINSIND', 'CYIENT', 'DABUR', 'DALBHARAT', 'DELHIVERY', 'DIVISLAB', 'DIXON', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT', 
                  'ETERNAL', 'EXIDEIND', 'FEDERALBNK', 'FORTIS', 'GAIL', 'GLENMARK', 'GMRAIRPORT', 'GODREJCP', 'GODREJPROP', 'GRANULES', 'GRASIM', 'HAL', 'HAVELLS', 
                  'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HFCL', 'HINDALCO', 'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HUDCO', 'ICICIBANK', 
                  'ICICIGI', 'ICICIPRULI', 'IDEA', 'IDFCFIRSTB', 'IEX', 'IGL', 'IIFL', 'INDHOTEL', 'INDIANB', 'INDIGO', 'INDUSINDBK', 'INDUSTOWER', 'INFY', 'INOXWIND', 'IOC', 
                  'IRB', 'IRCTC', 'IREDA', 'IRFC', 'ITC', 'JINDALSTEL', 'JIOFIN', 'JSL', 'JSWENERGY', 'JSWSTEEL', 'JUBLFOOD', 'KALYANKJIL', 'KAYNES', 'KEI', 'KFINTECH', 
                  'KOTAKBANK', 'KPITTECH', 'LAURUSLABS', 'LICHSGFIN', 'LICI', 'LODHA', 'LT', 'LTF', 'LTIM', 'LUPIN', 'M&M', 'M&MFIN', 'MANAPPURAM', 'MANKIND', 'MARICO', 
                  'MARUTI', 'MAXHEALTH', 'MAZDOCK', 'MCX', 'MFSL', 'MGL',  'MOTHERSON', 'MPHASIS', 'MUTHOOTFIN', 'NATIONALUM', 'NAUKRI', 'NBCC', 'NCC', 'NESTLEIND', 
                  'NHPC',  'NMDC', 'NTPC', 'NYKAA', 'OBEROIRLTY', 'OFSS', 'OIL', 'ONGC', 'PAGEIND', 'PATANJALI', 'PAYTM', 'PERSISTENT', 'PETRONET', 
                  'PFC', 'PGEL', 'PHOENIXLTD', 'PIDILITIND', 'PIIND', 'PNB', 'PNBHOUSING', 'POLICYBZR', 'POLYCAB', 'POONAWALLA', 'POWERGRID', 'PPLPHARMA', 'PRESTIGE', 'RBLBANK', 
                  'RECLTD', 'RELIANCE', 'RVNL', 'SAIL', 'SBICARD', 'SBILIFE', 'SBIN', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SJVN', 'SOLARINDS', 'SONACOMS', 
                  'SRF', 'SUNPHARMA', 'SUPREMEIND', 'SYNGENE', 'TATACHEM', 'TATACOMM', 'TATACONSUM', 'TATAELXSI', 'TATAPOWER', 'TATASTEEL', 'TATATECH', 
                  'TCS', 'TECHM', 'TIINDIA', 'TITAGARH', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TVSMOTOR', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'UNOMINDA', 'UPL', 
                  'VBL', 'VEDL', 'VOLTAS', 'WIPRO', 'YESBANK', 'ZYDUSLIFE']

#------------------------------------------------
nifty_auto = ['ASHOKLEY', 'MOTHERSON', 'BAJAJ-AUTO', 'BHARATFORG', 'TMPV', 'TIINDIA', 'MARUTI', 'BOSCHLTD', 'UNOMINDA', 'EICHERMOT', 'M&M', 
'SONACOMS', 'EXIDEIND', 'HEROMOTOCO', 'TVSMOTOR']
nifty_auto_index_movers = ['M&M', 'MARUTI', 'EICHERMOT', 'BAJAJ-AUTO', 'TVSMOTOR']
#------------------------------------------------


#------------------------------------------------
nifty_fin_services = ['360ONE', 'ABCAPITAL', 'ANGELONE', 'AXISBANK', 'BAJAJFINSV', 'BAJFINANCE', 'BSE', 'CAMS', 'CDSL', 'CHOLAFIN', 'HDFCAMC', 
'HDFCBANK', 'HDFCLIFE', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'IEX', 'IRFC', 'JIOFIN', 'KOTAKBANK', 'LICHSGFIN', 'LICI', 'LTF', 'MCX', 'MFSL', 
'MUTHOOTFIN', 'PAYTM', 'PFC', 'PNBHOUSING', 'POLICYBZR', 'RECLTD', 'SBICARD', 'SBILIFE', 'SBIN', 'SHRIRAMFIN']
nifty_fin_services_movers = ['BAJFINANCE','SHRIRAMFIN','SBILIFE','BAJAJFINSV']
#------------------------------------------------

#------------------------------------------------
nifty_fmcg = ['EMAMILTD', 'TATACONSUM', 'MARICO', 'NESTLEIND', 'HINDUNILVR', 'DABUR', 'BRITANNIA', 'GODREJCP', 'VBL', 'UNITDSPR', 'UBL', 'ITC', 
'COLPAL', 'PATANJALI', 'RADICO']
nifty_fmcg_movers = ['HINDUNILVR','ITC','BRITANNIA','NESTLEIND','TATACONSUM']
#------------------------------------------------

#------------------------------------------------
nifty_it_n_telecom = ['COFORGE', 'TECHM', 'LTIM', 'INFY', 'TCS', 'WIPRO', 'PERSISTENT', 'OFSS', 'HCLTECH', 'MPHASIS', 'AFFLE', 'BHARTIHEXA', 
'BSOFT', 'COFORGE', 'CYIENT', 'HEXT', 'HFCL', 'IDEA', 'INDUSTOWER', 'INTELLECT', 'KPITTECH', 'LTTS', 'MPHASIS', 'SONATSOFTW', 'TATACOMM', 
'TATAELXSI', 'TATATECH', 'ZENSARTECH']
nifty_it_n_telecom_movers = ['INFY','TCS','WIPRO','HCLTECH','TECHM']
#------------------------------------------------

#------------------------------------------------
nifty_media = ['NAZARA', 'SAREGAMA', 'PVRINOX', 'TIPSMUSIC', 'DBCORP', 'ZEEL', 'SUNTV', 'HATHWAY', 'NETWORK18', 'PFOCUS']
nifty_media_movers = ['PVRINOX','ZEEL','SUNTV', 'NAZARA', 'SAREGAMA', 'NETWORK18']
#------------------------------------------------

#------------------------------------------------
nifty_metal = ['HINDCOPPER', 'WELCORP', 'TATASTEEL', 'SAIL', 'LLOYDSME', 'JSL', 'JINDALSTEL', 'JSWSTEEL', 'APLAPOLLO', 'HINDALCO', 'ADANIENT', 
'VEDL', 'NATIONALUM', 'NMDC', 'HINDZINC']
nifty_metal_movers = ['TATASTEEL','JSWSTEEL','HINDALCO','JINDALSTEL', 'ADANIENT']
#------------------------------------------------

#------------------------------------------------
nifty_pharma_n_healthcare = ['ABBOTINDIA', 'AGARWALEYE', 'AJANTPHARM', 'ALKEM', 'APLLTD', 'APOLLOHOSP', 'ASTERDM', 'ASTRAZEN', 'AUROPHARMA', 
'BIOCON', 'CAPLIPOINT', 'CIPLA', 'COHANCE', 'CONCORDBIO', 'DIVISLAB', 'DRREDDY', 'EMCURE', 'ERIS', 'FORTIS', 'GLAND', 'GLAXO', 'GLENMARK', 
'GRANULES', 'INDGN', 'IPCALAB', 'JBCHEPHARM', 'JUBLPHARMA', 'KIMS', 'LALPATHLAB', 'LAURUSLABS', 'LUPIN', 'MANKIND', 'MAXHEALTH', 'MEDANTA', 
'METROPOLIS', 'NATCOPHARM', 'NEULANDLAB', 'NH', 'ONESOURCE', 'PFIZER', 'POLYMED', 'PPLPHARMA', 'RAINBOW', 'SAILIFE', 'SUNPHARMA', 'SYNGENE', 
'TORNTPHARM', 'VIJAYA', 'WOCKPHARMA', 'ZYDUSLIFE']
nifty_pharma_n_healthcare_movers = ['SUNPHARMA', 'CIPLA', 'DIVISLAB', 'DRREDDY', 'LUPIN', 'MAXHEALTH', 'APOLLOHOSP']
#------------------------------------------------


#------------------------------------------------
nifty_psu_banks = ['MAHABANK', 'INDIANB', 'CANBK', 'BANKINDIA', 'PNB', 'SBIN', 'BANKBARODA', 'IOB', 'UCOBANK', 'PSB', 'CENTRALBK', 'UNIONBANK']
nifty_private_banks = ['BANDHANBNK', 'RBLBANK', 'FEDERALBNK', 'AXISBANK', 'HDFCBANK', 'KOTAKBANK', 'ICICIBANK', 'IDFCFIRSTB', 'YESBANK', 'INDUSINDBK']
nifty_banks_index_movers = ['HDFCBANK', 'ICICIBANK', 'KOTAKBANK', 'AXISBANK', 'SBIN']
#------------------------------------------------

#------------------------------------------------
nifty_realty = ['PHOENIXLTD', 'GODREJPROP', 'SIGNATURE', 'OBEROIRLTY', 'LODHA', 'BRIGADE', 'SOBHA', 'DLF', 'PRESTIGE', 'ANANTRAJ']
nifty_realty_movers = ['DLF','GODREJPROP','PRESTIGE','PHOENIXLTD','LODHA']
#------------------------------------------------

#------------------------------------------------
nifty_cons_durables = ['CENTURYPLY', 'VGUARD', 'WHIRLPOOL', 'TITAN', 'VOLTAS', 'HAVELLS', 'CROMPTON', 'CERA', 'BATAINDIA', 'KAJARIACER', 'KALYANKJIL', 
'PGEL', 'BLUESTARCO', 'AMBER', 'DIXON']
nifty_cons_durables_movers = ['TITAN','VOLTAS','HAVELLS','DIXON','CROMPTON']
#------------------------------------------------

#------------------------------------------------
nifty_oil_n_gas = ['HINDPETRO', 'BPCL', 'IOC', 'OIL', 'IGL', 'ONGC', 'GAIL', 'RELIANCE', 'ATGL', 'AEGISLOG', 'GUJGASLTD', 'PETRONET', 'MGL', 'GSPL', 
'CASTROLIND']
nifty_oil_n_gas_movers = ['RELIANCE','IOC','BPCL','ONGC','GAIL']
#------------------------------------------------

#------------------------------------------------
nifty_chemicals = ['SWANCORP', 'ATUL', 'NAVINFLUOR', 'SUMICHEM', 'COROMANDEL', 'FLUOROCHEM', 'CHAMBLFERT', 'LINDEINDIA', 'PIIND', 'PIDILITIND', 'HSCL', 
'UPL', 'TATACHEM', 'BAYERCROP', 'DEEPAKNTR', 'AARTIIND', 'SOLARINDS', 'SRF', 'DEEPAKFERT', 'PCBL']
nifty_chemicals_movers = ['PIDILITIND','UPL','SRF','COROMANDEL','PIIND','SOLARINDS']
#------------------------------------------------

nifty_sectoral = nifty_auto + nifty_fin_services + nifty_fmcg + nifty_it_n_telecom + \
    nifty_media + nifty_metal + nifty_pharma_n_healthcare + nifty_psu_banks + nifty_private_banks + \
    nifty_realty + nifty_cons_durables + nifty_oil_n_gas + nifty_chemicals

nifty_movers = nifty_banks_index_movers + nifty_auto_index_movers + nifty_chemicals_movers + \
    nifty_fin_services_movers + nifty_fmcg_movers + nifty_pharma_n_healthcare_movers + \
    nifty_media_movers + nifty_metal_movers + nifty_realty_movers + nifty_cons_durables_movers + nifty_oil_n_gas_movers



nifty_midcap150 = ['360ONE', '3MINDIA', 'ACC', 'AIAENG', 'APLAPOLLO','AUBANK', 'AWL', 'ABBOTINDIA', 'ATGL', 'ABCAPITAL',
    'AJANTPHARM', 'ALKEM', 'APARINDS', 'APOLLOTYRE', 'ASHOKLEY', 'ASTRAL', 'AUROPHARMA', 'BSE', 'BALKRISIND', 'BANKINDIA',
    'MAHABANK', 'BERGEPAINT', 'BDL', 'BHARATFORG', 'BHEL', 'BHARTIHEXA', 'BIOCON', 'BLUESTARCO', 'CRISIL', 'COCHINSHIP',
    'COFORGE', 'COLPAL', 'CONCOR', 'COROMANDEL', 'CUMMINSIND', 'DABUR', 'DALBHARAT', 'DEEPAKNTR', 'DIXON', 'ENDURANCE',
    'ESCORTS', 'EXIDEIND', 'NYKAA', 'FEDERALBNK', 'FACT', 'FORTIS', 'GVT&D', 'GMRAIRPORT', 'GICRE', 'GLAXO',
    'GLENMARK', 'MEDANTA', 'GODFRYPHLP', 'GODREJIND', 'GODREJPROP', 'FLUOROCHEM', 'GUJGASLTD', 'HDFCAMC', 'HEROMOTOCO', 'HEXT',
    'HINDPETRO', 'POWERINDIA', 'HONAUT', 'HUDCO', 'ICICIPRULI', 'IDBI', 'IDFCFIRSTB', 'IRB', 'ITCHOTELS', 'INDIANB',
    'IOB', 'IRCTC', 'IREDA', 'IGL', 'INDUSTOWER', 'INDUSINDBK', 'IPCALAB', 'JKCEMENT', 'JSWINFRA', 'JSL',
    'JUBLFOOD', 'KPRMILL', 'KEI', 'KPITTECH', 'KALYANKJIL', 'LTF', 'LTTS', 'LICHSGFIN', 'LINDEINDIA', 'LLOYDSME',
    'LUPIN', 'MRF', 'M&MFIN', 'MANKIND', 'MARICO', 'MFSL', 'MOTILALOFS', 'MPHASIS', 'MUTHOOTFIN', 'NHPC',
    'NLCINDIA', 'NMDC', 'NTPCGREEN', 'NATIONALUM', 'NAM-INDIA', 'OBEROIRLTY', 'OIL', 'PAYTM', 'OFSS', 'POLICYBZR',
    'PIIND', 'PAGEIND', 'PATANJALI', 'PERSISTENT', 'PETRONET', 'PHOENIXLTD', 'POLYCAB', 'PREMIERENE', 'PRESTIGE', 'PGHH',
    'RVNL', 'SBICARD', 'SJVN', 'SRF', 'SCHAEFFLER', 'SONACOMS', 'SAIL', 'SUNDARMFIN', 'SUPREMEIND', 'SUZLON',
    'SWIGGY', 'SYNGENE', 'TATACOMM', 'TATAELXSI', 'TATAINVEST', 'TATATECH', 'NIACL', 'THERMAX', 'TORNTPOWER', 'TIINDIA',
    'UCOBANK', 'UNOMINDA', 'UPL', 'UNIONBANK', 'UBL', 'VMM', 'IDEA', 'VOLTAS', 'WAAREEENER', 'YESBANK']

nifty_smallcap250 = ['AADHARHFC', 'AARTIIND', 'AAVAS', 'ABFRL', 'ABLBL', 'ABREL', 'ABSLAMC', 'ACE', 'ACMESOLAR', 'AEGISLOG', 
'AEGISVOPAK', 'AFCONS', 'AFFLE', 'AGARWALEYE',  'AIIL', 'AKUMS', 'AKZOINDIA', 'ALKYLAMINE',  'ALOKINDS', 'AMBER', 'ANANDRATHI',
'ANANTRAJ',  'ANGELONE', 'APLLTD', 'APTUS', 'ARE&M', 'ASAHIINDIA', 'ASTERDM', 'ASTRAZEN', 'ATHERENERG', 'ATUL', 'BALRAMCHIN',
'BANDHANBNK', 'BASF', 'BATAINDIA', 'BAYERCROP', 'BBTC', 'BEML', 'BIKAJI', 'BLS', 'BLUEDART', 'BLUEJET', 'BRIGADE', 'BSOFT',
'CAMPUS', 'CAMS', 'CANFINHOME', 'CAPLIPOINT', 'CARBORUNIV', 'CASTROLIND', 'CCL', 'CDSL', 'CEATLTD', 'CENTRALBK', 'CENTURYPLY', 'CERA',
'CESC', 'CGCL', 'CHALET', 'CHAMBLFERT', 'CHENNPETRO', 'CHOICEIN', 'CHOLAHLDNG', 'CLEAN', 'COHANCE', 'CONCORDBIO',
'CRAFTSMAN', 'CREDITACC', 'CROMPTON', 'CUB', 'CYIENT', 'DATAPATTNS', 'DBREALTY', 'DCMSHRIRAM', 'DEEPAKFERT', 'DELHIVERY',
'DEVYANI', 'DOMS', 'ECLERX', 'EIDPARRY', 'EIHOTEL', 'ELECON', 'ELGIEQUIP', 'EMAMILTD', 'EMCURE', 'ENGINERSIN',
'ERIS', 'FINCABLES', 'FINPIPE', 'FIRSTCRY', 'FIVESTAR', 'FORCEMOT', 'FSL', 'GESHIP', 'GILLETTE', 'GLAND', 'GMDCLTD', 'GODIGIT',
'GODREJAGRO', 'GPIL', 'GRANULES', 'GRAPHITE', 'GRAVITA', 'GRSE', 'GSPL', 'HAPPSTMNDS', 'HBLENGINE', 'HEG',
'HFCL', 'HINDCOPPER', 'HOMEFIRST', 'HONASA', 'HSCL', 'IEX', 'IFCI', 'IGIL', 'IIFL', 'IKS', 'INDGN', 'INDIACEM', 'INDIAMART', 'INOXINDIA',
'INOXWIND', 'INTELLECT', 'IRCON', 'ITI', 'J&KBANK', 'JBCHEPHARM', 'JBMA', 'JINDALSAW', 'JKTYRE', 'JMFINANCIL', 'JPPOWER', 'JSWCEMENT',
'JUBLINGREA', 'JUBLPHARMA', 'JWL', 'JYOTHYLAB', 'JYOTICNC', 'KAJARIACER', 'KARURVYSYA', 'KAYNES', 'KEC', 'KFINTECH', 'KIMS', 'KIRLOSBROS',
'KIRLOSENG', 'KPIL', 'KSB', 'LALPATHLAB',  'LATENTVIEW', 'LAURUSLABS', 'LEMONTREE', 'LTFOODS', 'MAHSCOOTER', 'MAHSEAMLES',
'MANAPPURAM', 'MANYAVAR', 'MAPMYINDIA', 'MCX',  'METROPOLIS', 'MGL', 'MINDACORP', 'MMTC', 'MRPL', 'MSUMI',
'NATCOPHARM', 'NAVA', 'NAVINFLUOR', 'NBCC', 'NCC', 'NETWEB', 'NEULANDLAB', 'NEWGEN', 'NH', 'NIVABUPA', 'NSLNISP', 'NUVAMA',
'NUVOCO', 'OLAELEC', 'OLECTRA', 'ONESOURCE',  'PCBL', 'PFIZER', 'PGEL', 'PNBHOUSING', 'POLYMED', 'POONAWALLA', 'PPLPHARMA', 'PRAJIND',
'PTCIL', 'PVRINOX', 'RADICO', 'RAILTEL', 'RAINBOW', 'RAMCOCEM', 'RBLBANK', 'RCF', 'REDINGTON', 'RELINFRA', 'RHIM', 'RITES',
'RKFORGE', 'RPOWER', 'RRKABEL', 'SAGILITY', 'SAILIFE', 'SAMMAANCAP', 'SAPPHIRE', 'SARDAEN', 'SAREGAMA', 'SBFC', 'SCHNEIDER', 'SCI',
'SHYAMMETL', 'SIGNATURE', 'SOBHA', 'SONATSOFTW', 'STARHEALTH', 'SUMICHEM', 'SUNDRMFAST', 'SUNTV', 'SWANCORP', 'SYRMA',
'TARIL', 'TATACHEM', 'TBOTEK', 'TECHNOE', 'TEJASNET', 'THELEELA',  'TIMKEN', 'TITAGARH', 'TRIDENT', 'TRITURBINE',
'TRIVENI', 'TTML',  'USHAMART', 'UTIAMC', 'VENTIVE', 'VGUARD', 'VIJAYA', 'VTL', 'WELCORP', 'WELSPUNLIV', 'WHIRLPOOL', 'WOCKPHARMA',
'ZEEL', 'ZENSARTECH', 'ZENTEC', 'ZFCVINDIA']

nifty_mid_small_caps = nifty_midcap150 + nifty_smallcap250

nifty_cash = ['20MICRONS', '21STCENMGM', '360ONE', '3IINFOLTD', '3MINDIA', '3PLAND', '5PAISA', '63MOONS', 'A2ZINFRA', 
    'AAKASH', 'AAREYDRUGS', 'AARON', 'AARTECH', 'AARTIDRUGS', 'AARTIIND', 'AARTIPHARM', 'AARTISURF', 'AARVI', 'AAVAS',
    'ABCAPITAL', 'ABCOTS', 'ABDL', 'ABFRL', 'ABGSEC', 'ABINFRA', 'ABLBL', 'ABMINTLLTD', 'ABREL', 'ABSLAMC',
    'ABSLBANETF', 'ABSLNN50ET', 'ABSLPSE', 'ABSLLIQUID', 'ACC', 'ACCELYA', 'ACCURACY', 'ACE', 'ACEINTEG', 'ACLGATI',
    'ACMESOLAR', 'ACUTAAS', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'ADFFOODS', 'ADL', 'ADOR',
    'ADROITINFO', 'ADVANCE', 'ADVANIHOTR', 'ADVENZYMES', 'AEGISLOG', 'AEGISVOPAK', 'AEROENTER', 'AEROFLEX',
    'AERONEU', 'AETHER', 'AFCONS', 'AFFLE', 'AFFORDABLE', 'AFIL', 'AGARIND', 'AGARWALEYE', 'AGI', 'AGIIL',
    'AGROPHOS', 'AGRITECH', 'AHLEAST', 'AHLADA', 'AHLUCONT', 'AIAENG', 'AIIL', 'AIROLAM', 'AIRAN',
    'AIAENG', 'AJANTPHARM', 'AJAXENGG', 'AJMERA', 'AJOONI', 'AJOONI', 'AKASH', 'AKG', 'AKI', 'AKSHOPTFBR',
    'AKSHARCHEM', 'AKUMS', 'AKZOINDIA', 'ALANKIT', 'ALBERTDAVD', 'ALEMBICLTD', 'ALIVUS', 'ALKALI', 'ALKEM', 'ALKYLAMINE',
    'ALLCARGO', 'ALLDIGI', 'ALLTIME', 'ALMONDZ', 'ALOKINDS', 'ALPA', 'ALPHAGEO', 'ALPHA', 'ALPHAETF', 'ALPL30IETF',
    'ALPSINDUS', 'AMBER', 'AMBIKCO', 'AMBICAAGAR', 'AMBUJACEM', 'AMDIND', 'AMJLAND', 'AMNPLST',
    'AMRUTANJAN', 'ANANDRATHI', 'ANANTRAJ', 'ANDHRAPAP', 'ANDHRSUGAR', 'ANGELONE', 'ANIKINDS', 'ANMOL', 'ANTGRAPHIC',
    'ANTELOPUS', 'ANUP', 'ANURAS', 'AONEGOLD', 'AONELIQUID', 'AONETOTAL', 'APARINDS', 'APCOTEXIND', 'APCL',
    'APLAPOLLO', 'APLLTD', 'APOLLO', 'APOLLOHOSP', 'APOLLOPIPE', 'APOLSINHOT', 'APOLLOTYRE', 'APTECHT', 'APTUS', 'APEX',
    'ARE&M', 'ARIHANTCAP', 'ARIHANTSUP', 'ARISINFRA', 'ARKADE', 'ARMANFIN', 'AROGRANITE', 'ARROWGREEN', 'ARTEMISMED', 'ARTNIRMAN',
    'ARVEE', 'ARVINDFASN', 'ARVIND', 'ARVSMART', 'ARSSBL', 'ASAHIINDIA', 'ASAHISONG', 'ASHAPURMIN', 'ASHIANA',
    'ASHIMASYN', 'ASHOKAMET', 'ASHOKLEY', 'ASHOKA', 'ASIANTILES', 'ASIANHOTNR', 'ASIANPAINT', 'ASKAUTOLTD',
    'ASALCBR', 'ASPINWALL', 'ASTEC', 'ASTERDM', 'ASTRAZEN', 'ASTRAL', 'ASTRAMICRO', 'ASTRON', 'ATAM', 'ATGL',
    'ATL', 'ATLANTAELE', 'ATLASCYCLE', 'ATULAUTO', 'ATUL', 'AUBANK', 'AURIGROW', 'AURIONPRO', 'AURUM',
    'AUSOMENT', 'AUTOAXLES', 'AUTOIETF', 'AUTOBEES', 'AUTOIND', 'AVALON', 'AVANTEL', 'AVANTIFEED', 'AVL', 'AVONMORE',
    'AVROIND', 'AVTNPL', 'AWFIS', 'AWL', 'AXISBANK', 'AXISGOLD', 'AXISILVER',  'AXISTECETF', 'AXISVALUE',
    'AXITA', 'AYMSYNTEX', 'AZAD', 'BAGFILMS', 'BAIDFIN', 'BAJAJ-AUTO', 'BAJAJCON', 'BAJAJELEC', 'BAJFINANCE', 'BAJAJFINSV',
    'BAJAJHCARE', 'BAJAJHFL', 'BAJAJHIND', 'BAJAJHLDNG', 'BAJEL', 'BALAJEE', 'BALAJITELE', 'BALAMINES', 'BALAXI', 'BALKRISIND',
    'BALKRISHNA', 'BALPHARMA', 'BALRAMCHIN', 'BANDHANBNK', 'BANKA', 'BANKBARODA', 'BANKBEES', 'BANKETF', 'BANKETFADD', 'BANKIETF',
    'BANKINDIA',  'BANKPSU', 'BANSALWIRE', 'BANSWRAS', 'BASF', 'BATAINDIA', 'BAYERCROP', 'BBETF0430', 'BBETF0431',
    'BBETF0432', 'BBETF0433', 'BBL', 'BBTC', 'BBTCL', 'BCG', 'BCLIND', 'BCONCEPTS', 'BDL', 'BEARDSELL',
    'BECTORFOOD', 'BEDMUTHA', 'BEL', 'BELRISE', 'BEML', 'BERGEPAINT', 'BESTAGRO', 'BFINVEST', 'BGRENERGY', 'BHAGERIA',
    'BHAGCHEM', 'BHAGYANGR', 'BHANDARI', 'BHARATFORG', 'BHARATGEAR', 'BHARATRAS', 'BHARATSE', 'BHARATWIRE', 'BHARTIARTL', 'BHARTIHEXA',
    'BHEL', 'BHANDARI', 'BIGBLOC', 'BIKAJI', 'BIL', 'BILVYAPAR', 'BINANIIND', 'BIOCON', 'BIOFILCHEM', 'BIRLACABLE',
    'BIRLACORPN', 'BIRLANU', 'BIRLAMONEY', 'BIRET', 'BIRLATYRE', 'BLAL', 'BLBLIMITED', 'BLISSGVS', 'BLKASHYAP', 'BLSE',
    'BLS', 'BLUEDART', 'BLUEJET', 'BLUESTARCO', 'BLUSPRING', 'BMWVENTLTD', 'BODALCHEM', 'BOMDYEING', 'BORANA', 'BOROLTD',
    'BORORENEW', 'BOROSCI', 'BOSCHLTD', 'BPCL', 'BPL', 'BRIGADE', 'BRITANNIA', 'BRNL', 'BROOKS', 'BSE',
    'BSHSL', 'BSL', 'BSOFT', 'BTML', 'BUTTERFLY', 'BYKE', 'CALSOFT', 'CAMPUS', 'CANBK',
    'CANFINHOME', 'CANHLIFE', 'CANTABIL', 'CAPACITE', 'CAPINVIT', 'CAPITALSFB', 'CAPLIPOINT', 'CAPTRUST', 'CARBORUNIV', 'CARERATING',
    'CASTROLIND', 'CCHHL', 'CCL', 'CEATLTD', 'CEIGALL', 'CELEBRITY', 'CELLO', 'CEMPRO', 'CENTENKA', 'CENTUM',
    'CENTURYPLY', 'CERA', 'CESC', 'CGCL', 'CGPOWER', 'CHALET', 'CHAMBLFERT', 'CHEMBOND', 'CHEMBONDCH', 'CHEMCON',
    'CHEMFAB', 'CHEMPLASTS', 'CHENNPETRO', 'CHEVIOT', 'CHOLAFIN', 'CHOLAHLDNG', 'CIEINDIA', 'CIGNITITEC', 'CINELINE', 'CINEVISTA',
    'CIPLA', 'CLEAN', 'CLEDUCATE', 'CLSEL', 'CMSINFO', 'COALINDIA', 'COASTCORP', 'COCHINSHIP', 'COFORGE', 'COHANCE',
    'COLPAL', 'COMSYN', 'COMPINFO', 'COMPUSOFT', 'CONFIPET', 'CONSOFINVT', 'CONSUMER', 'CONSUMIETF', 'CORALFINAC', 'CORDSCABLE',
    'COROMANDEL', 'COSMOFIRST', 'COUNCODOS', 'CPCAP', 'CPEDU', 'CRAFTSMAN', 'CREATIVE', 'CREATIVEYE', 'CREDITACC', 'CREST',
    'CRISIL', 'CROMPTON', 'CROWN', 'CSBBANK', 'CSLFINANCE', 'CTE', 'CUB', 'CUBEXTUB', 'CUMMINSIND', 'CUPID',
    'CYBERMEDIA', 'CYBERTECH', 'CYIENT', 'CYIENTDLM', 'DABUR', 'DALBHARAT', 'DALMIARF', 'DALMIASUG', 'DAMCAPITAL', 'DAMODARIND',
    'DANGEE', 'DATAMATICS', 'DATAPATTNS', 'DAVANGERE', 'DBEIL', 'DBL', 'DBOL', 'DBREALTY', 'DBSTOCKBRO', 'DCAL',
    'DCBBANK', 'DCM', 'DCMFINSERV', 'DCMNVL', 'DCMSHRIRAM', 'DCMSRIND', 'DCW', 'DCXINDIA', 'DDEVPLSTIK', 'DECCANCE',
    'DEEDEV', 'DEEPINDS', 'DELHIVERY', 'DELPHIFX', 'DELTA', 'DELTACORP', 'DELTAMAGNT', 'DEN', 'DENORA', 'DENTA',
    'DEVIT', 'DEVX', 'DEVYANI', 'DHAMPURSUG', 'DHANBANK', 'DHANI', 'DHARMAJ', 'DHUNINV', 'DIACABS', 'DIAMINESQ',
    'DICIND', 'DIFFNKG', 'DIGIDRIVE', 'DIGISPICE', 'DIGJAMLMTD', 'DIL', 'DISHTV', 'DIXON', 'DJML', 'DLF',
    'DMART', 'DMCC', 'DNAMEDIA', 'DODLA', 'DOLATALGO', 'DOLLAR', 'DOLPHIN', 'DOMS', 'DONEAR', 'DPSCLTD',
    'DRCSYSTEMS', 'DREAMFOLKS', 'DREDGECORP', 'DRREDDY', 'DSIJ', 'DSSL', 'DTIL', 'DUCON', 'DVL', 'DWARKESH',
    'DYNPRO', 'DYCL', 'E2E', 'EASEMYTRIP', 'EBBETF0430', 'EBBETF0431', 'EBBETF0432', 'EBBETF0433', 'ECAPINSURE',
    'ECLERX', 'ECOSMOBLTY', 'EDELWEISS', 'EFCIL', 'EGOLD', 'EIDPARRY', 'EIHAHOTELS', 'EIHOTEL', 'EIMCOELECO', 'EKC',
    'ELDEHSG', 'ELECON', 'ELGIEQUIP', 'ELGIRUBCO', 'ELIN', 'ELLEN', 'EMAMILTD', 'EMAMIPAP', 'EMAMIREAL', 'EMBDL',
    'EMCURE', 'EMIL', 'EMMBI', 'EMSLIMITED', 'EMUDHRA', 'ENDURANCE', 'ENERGYDEV', 'ENGINERSIN', 'ENIL', 'ENTERO',
    'EPL', 'EQUITASBNK', 'ERIS', 'ESABINDIA', 'ESAFSFB', 'ESCORTS', 'ESTER', 'ETERNAL', 'ETHOSLTD', 'EUROTEXIND',
    'EVEREADY', 'EVERESTIND', 'EVINDIA', 'EVIETF', 'EXCELINDUS', 'EXICOM', 'EXIDEIND', 'EXPLEOSOL', 'EXXARO', 'FABTECH',
    'FACT', 'FAIRCHEMOR', 'FAZE3Q', 'FCSSOFT', 'FDC', 'FEDFINA', 'FEDERALBNK', 'FIBERWEB', 'FIEMIND', 'FILATEX',
    'FILATFASH', 'FINEORG', 'FINKURVE', 'FINOPB', 'FINPIPE', 'FIVESTAR', 'FLEXIADD', 'FLEXITUFF', 'FLFL', 'FLIPKART',
    'FLUOROCHEM', 'FMCGIETF', 'FMGOETZE', 'FMNL', 'FOCUS', 'FOODSIN', 'FORCEMOT', 'FORTIS', 'FOSECOIND', 'FSL',
    'FUSION', 'GABRIEL', 'GAEL', 'GAIL', 'GALAPREC', 'GALAXYSURF', 'GALLANTT', 'GANDHAR', 'GANDHITUBE', 'GANECOS',
    'GANESHBE', 'GANESHCP', 'GANESHHOU', 'GANGAFORGE', 'GARFIBRES', 'GARUDA', 'GATECH', 'GATECHDVR', 'GATEWAY', 'GEEKAYWIRE',
    'GEMAROMA', 'GENCON', 'GENESYS', 'GENUSPAPER', 'GENUSPOWER', 'GEOJITFSL', 'GEPIL', 'GESHIP', 'GHCL', 'GHCLTEXTIL',
    'GICHSGFIN', 'GICRE', 'GILLANDERS', 'GILLETTE', 'GINNIFILA', 'GIPCL', 'GIRIRAJ', 'GKNDRIVE', 'GLAND', 'GLAXO',
    'GLENMARK', 'GLOBAL', 'GLOBALE', 'GLOBE', 'GLOBUSSPR', 'GLOSTERLTD', 'GMBREW', 'GMDCLTD', 'GMMPFAUDLR', 'GMRAIRPORT',
    'GMRP&UI', 'GNA', 'GNFC', 'GOCOLORS', 'GODAVARIB', 'GODFRYPHLP', 'GODIGIT', 'GODREJAGRO', 'GODREJCP', 'GODREJIND',
    'GODREJPROP', 'GOKEX', 'GOKUL', 'GOKULAGRO', 'GOLD1', 'GOLD360', 'GOLDIAM', 'GOLDBEES', 'GOLDETF', 'GOLDETFADD',
    'GOLDIETF', 'GOLDTECH', 'GOODLUCK', 'GOPAL', 'GOYALALUM', 'GPIL', 'GPPL', 'GPTHEALTH', 'GPTINFRA', 'GRANULES',
    'GRAPHITE', 'GRASIM', 'GRAVITA', 'GREAVESCOT', 'GREENLAM', 'GREENPANEL', 'GREENPLY', 'GREENPOWER', 'GRINDWELL', 'GRINFRA',
    'GRMOVER', 'GROWWDEFNC', 'GROWWGOLD', 'GROWWLIQID', 'GROWWLOVOL', 'GROWWMOM50', 'GROWWN200', 'GROWWNET', 'GROWWPOWER', 'GROWWRAIL', 'GROWWRLTY',
    'GROWWSLVR', 'GRPLTD', 'GRSE', 'GSS', 'GTL', 'GTLINFRA', 'GTPL', 'GUFICBIO', 'GULFOILLUB', 'GULFPETRO', 'GULPOLY',
    'GUJALKALI', 'GUJGASLTD', 'GUJRAFFIA', 'GUJTHEM', 'GULFOILLUB', 'GVPIL', 'GVPTECH', 'GVKPIL', 'HAPPSTMNDS', 'HAPPYFORGE',
    'HARDOLI', 'HARDWYN', 'HARRMALAYA', 'HARSHA', 'HATHWAY', 'HATSUN', 'HAVELLS', 'HBLENGINE', 'HBSL', 'HCC',
    'HCL-INSYS', 'HCLTECH', 'HCLTECHNOLOGIES', 'HDFCAMC', 'HDFCBANK', 'HDFCBSE500', 'HDFCGOLD', 'HDFCGROWTH', 'HDFCLIQUID', 'HDFCLOWVOL',
    'HDFCMID150', 'HDFCMOMENT', 'HDFCNEXT50', 'HDFCNIF100', 'HDFCNIFBAN', 'HDFCNIFIT',  'HDFCPVTBAN', 'HDFCQUAL', 
    'HDFCSILVER', 'HDFCSML250', 'HDFCVALUE', 'HDFCPSUBK', 'HEADSUP', 'HEALTHADD', 'HEALTHY', 'HECPROJECT', 'HEG', 'HEIDELBERG',
    'HEMIPROP', 'HERANBA', 'HERCULES', 'HERITGFOOD', 'HEROMOTOCO', 'HESTERBIO', 'HEUBACHIND', 'HEXATRADEX', 'HGS', 'HIKAL',
    'HIL', 'HILTON', 'HINDALCO', 'HINDCON', 'HINDCOPPER', 'HINDMOTORS', 'HINDOILEXP', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC',
    'HINDWAREAP', 'HIRECT', 'HISARMETAL', 'HITECH', 'HITECHCORP', 'HLEGLAS', 'HLVLTD', 'HMAAGRO', 'HMVL', 'HNGSNGBEES',
    'HOMEFIRST', 'HONASA', 'HONAUT', 'HONDAPOWER', 'HOVS', 'HPAL', 'HPIL', 'HSCL', 'HTMEDIA', 'HUBTOWN',
    'HUDCO', 'HUHTAMAKI', 'HYUNDAI', 'IBULHSGFIN', 'ICICIB22', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'ICIL', 'ICRA',
    'IDBI', 'IDEA', 'IDEAFORGE', 'IDFCFIRSTB', 'IEX', 'IFBIND', 'IFCI', 'IFGLEXPOR', 'IGARASHI', 'IGL',
    'IGPL', 'IIFL', 'IIFLCAPS', 'IKIO', 'IMAGICAA', 'IMPAL', 'INCREDIBLE', 'INDBANK', 'INDIACEM', 'INDIAGLYCO',
    'INDIAMART', 'INDIANB', 'INDIANHUME', 'INDIANCARD', 'INDIGO', 'INDIGOPNTS', 'INDNIPPON', 'INDOAMIN', 'INDOBORAX', 'INDOCO',
    'INDOFARM', 'INDORAMA', 'INDOWIND', 'INDRAPRASTHA', 'INDTERRAIN', 'INDUSINDBK', 'INDUSTOWER', 'INFIBEAM', 'INFOMEDIA', 'INFY',
    'INGERRAND', 'INNOVACAP', 'INNOVANA', 'INOXGREEN', 'INOXINDIA', 'INOXWIND', 'INSECTICID', 'INSPIRISYS', 'INTELLECT', 'INTENTECH',
    'INTERARCH', 'INTLCONV', 'IOB', 'IOC', 'IOCL', 'IONEXCHANG', 'IPCALAB', 'IRB', 'IRBINVIT', 'IRCON',
    'IRCTC', 'IRFC', 'IREDA', 'IRIS', 'IRISDOREME', 'IRMENERGY', 'ISFT', 'ISGEC', 'ISHANCH', 'IT',
    'ITC', 'ITI', 'ITBEES', 'ITDC', 'ITETF', 'ITETFADD', 'ITIETF', 'IVC', 'IVP', 'IVZINGOLD',
    'IOLCP', 'IXIGO', 'J&KBANK', 'JAGRAN', 'JAGSNPHARM', 'JAIBALAJI', 'JAICORPLTD', 'JAMNAAUTO', 'JARO',
    'JASH', 'JAYAGROGN', 'JAYBARMARU', 'JAYNECOIND', 'JAYSREETEA', 'JBCHEPHARM', 'JBMA', 'JCHAC', 'JETAIRWAYS', 'JETFREIGHT',
    'JHS', 'JINDALPHOT', 'JINDALPOLY', 'JINDALSAW', 'JINDALSTEL', 'JINDWORLD', 'JIOFIN', 'JISLDVREQS', 'JISLJALEQS', 'JITFINFRA',
    'JKCEMENT', 'JKIL', 'JKLAKSHMI', 'JKPAPER', 'JKTYRE', 'JLHL', 'JMFINANCIL', 'JNKINDIA', 'JOCIL', 'JOTINDRA',
    'JPOLYINVST', 'JPPOWER', 'JSFB', 'JSL', 'JSWINFRA', 'JSWENERGY', 'JSWHL', 'JSWSTEEL', 'JTEKTINDIA', 'JTLIND',
    'JUBLFOOD', 'JUBLINGREA', 'JUBLPHARMA', 'JUNIPER', 'JUSTDIAL', 'JWL', 'JYOTHYLAB', 'JYOTICNC', 'JYOTISTRUC', 'KABIRDAS',
    'KABRAEXTRU', 'KAJARIACER', 'KAKATCEM', 'KALAMANDIR', 'KALYANI', 'KALYANIFRG', 'KALYANKJIL', 'KAMATHOTEL', 'KAMDHENU', 'KAMOPAINTS',
    'KANANIIND', 'KANORICHEM', 'KANPRPLA', 'KANSAINER', 'KAPSTON', 'KARURVYSYA', 'KAVDEFENCE', 'KAVVERITEL', 'KAYA', 'KAYNES',
    'KCP', 'KCPSUGIND', 'KDDL', 'KECL', 'KEC', 'KEI', 'KEEPLEARN', 'KELLTONTEC', 'KERNEX', 'KESORAMIND',
    'KEYFINSERV', 'KFINTECH', 'KHADIM', 'KHAICHEM', 'KHANDSE', 'KHFM', 'KHIL', 'KICL', 'KILITCH', 'KIMS',
    'KINGFA', 'KIOCL', 'KIRIINDUS', 'KIRLOSBROS', 'KIRLOSENG', 'KIRLPNU', 'KIRRTMT', 'KITEX', 'KKCL', 'KMEW',
    'KNRCON', 'KOHINOOR', 'KOKUYOCMLN', 'KOLTEPATIL', 'KOPRAN', 'KOTAKBANK', 'KOTHARIPET', 'KOTHARIPRO', 'KOTARISUG', 'KPIGREEN',
    'KPIL', 'KPITTECH', 'KPRMILL', 'KRBL', 'KREBSBIO', 'KRIDHANINF', 'KRISHANA', 'KRISHIVAL', 'KRITI', 'KRITINUT',
    'KRN', 'KROSS', 'KRSNAA', 'KRYSTAL', 'KSCL', 'KSB', 'KSHITIJPOL', 'KSOLVES', 'KUANTUM', 'LAL',
    'LALPATHLAB', 'LAMBODHARA', 'LANCORHOL', 'LANDMARK', 'LAOPALA', 'LASA', 'LATENTVIEW', 'LATTEYS', 'LAURUSLABS', 'LAXMICOT',
    'LAXMIDENTL', 'LCCINFOTEC', 'LEMONTREE', 'LENSKART', 'LGHL', 'LGBBROSLTD', 'LGEINDIA', 'LIBAS', 'LIBERTSHOE', 'LICHSGFIN',
    'LICI', 'LICMFGOLD', 'LICNETFN50', 'LICNETFSEN', 'LICNFNHGP', 'LICNMID100', 'LIKHITHA', 'LINC', 'LINCOLN', 'LINDEINDIA',
    'LIQUID', 'LIQUID1', 'LIQUIDADD', 'LIQUIDBEES', 'LIQUIDCASE', 'LIQUIDETF', 'LIQUIDSBI', 'LODHA', 'LOKESHMACH', 'LORDSCHLO',
    'LOTUSDEV', 'LOTUSEYE', 'LOVABLE', 'LOYALTEX', 'LPDC', 'LT', 'LTF', 'LTFOODS', 'LTGILTBEES', 'LTGILTCASE',
    'LTIM', 'LTTS', 'LUMAXIND', 'LUMAXTECH', 'LUPIN', 'LUXIND', 'LYKALABS', 'LYPSAGEMS', 'MAANALU', 'MACH',
    'MACPOWER', 'MADHAV', 'MADHUCON', 'MAGADSUGAR', 'MAGNUM', 'MAHAPEXLTD', 'MAHASTEEL', 'MAHESHWARI', 'MAHSCOOTER', 'MAHSEAMLES',
    'MAITHANALL', 'MALLCOM', 'MALUPAPER', 'MAMATA', 'MANAKCOAT', 'MANAKSIA', 'MANAKSTEEL', 'MANALIPETC', 'MANAPPURAM', 'MANBA',
    'MANCREDIT', 'MANGLMCEM', 'MANGALAM', 'MANINDS', 'MANINFRA', 'MANKIND', 'MANOMAY', 'MANORAMA', 'MANORG', 'MANYAVAR',
    'MARALOVER', 'MARATHON', 'MARICO', 'MARINE', 'MARKOLINES', 'MARKSANS', 'MARUTI', 'MASFIN', 'MASTEK', 'MASTERTR',
    'MATRIMONY', 'MAWANASUG', 'MAXESTATES', 'MAXHEALTH', 'MAXIND', 'MAYURUNIQ', 'MAZDA', 'MAZDOCK', 'MBAPL', 'MBEL',
    'MBLINFRA', 'MCLEODRUSS', 'MCLOUD', 'MCX', 'MDRIVE', 'MEDANTA', 'MEDIASSIST', 'MEDICAMEQ', 'MEDICO', 'MEDPLUS',
    'MEGASOFT', 'MEGASTAR', 'MEIL', 'MENONBE', 'METROBRAND', 'METROPOLIS', 'MFSL', 'MGEL', 'MGL', 'MHLXMIRU',
    'MID150', 'MID150BEES', 'MID150CASE', 'MIDCAP', 'MIDCAPETF', 'MIDCAPIETF', 'MIDHANI', 'MIDSELIETF', 'MIDSMALL', 'MILIND',
    'MINDACORP', 'MINDSPACE', 'MINDTECK', 'MIRCELECTR', 'MIRZAINT', 'MITCON', 'MITTAL', 'MKPL', 'MMFL', 'MMP',
    'MMTC', 'MNKINC', 'MNTL', 'MOALPHA50', 'MOCAPITAL', 'MODEFENCE', 'MODI', 'MODISONLTD', 'MODISONLTD', 'MODTHREAD',
    'MODIRUBBER', 'MOGOLD', 'MOGSEC', 'MOHEALTH', 'MOHITIND', 'MOIL', 'MOKSH', 'MOLDTECH', 'MOLDTKPAC', 'MOL',
    'MOLOWVOL', 'MOM100', 'MOM30IETF', 'MOM50', 'MOMENTUM', 'MOMENTUM30', 'MOMENTUM50', 'MOMGF', 'MOMIDMTM', 'MOMOMENTUM',
    'MON100', 'MON50EQUAL', 'MONARCH', 'MONQ50', 'MONEYBOXX', 'MONTECARLO', 'MOREPENLAB', 'MOSCHIP',
    'MOSILVER', 'MOSMALL250', 'MOTILALOFS', 'MOTOGENFIN', 'MOTOUR', 'MOVALUE', 'MPSLTD', 'MRF', 'MRPL', 'MSPL',
    'MSUMI', 'MTARTECH', 'MTEDUCARE', 'MTNL', 'MUKANDLTD', 'MUKKA', 'MUKTAARTS', 'MULTICAP', 'MUNJALAU', 'MUNJALSHOW', 'MURUDCERA',
    'MUTHOOTCAP', 'MUTHOOTFIN', 'MUTHOOTMF', 'MVGJL', 'MWL', 'NACLIND', 'NAGAFERT', 'NAGREEKEXP', 'NAHARCAP', 'NAHARINDUS',
    'NAHARPOLY', 'NAHARSPING', 'NAKSH', 'NAM-INDIA', 'NARMADA', 'NATCOPHARM', 'NATHBIOGEN', 'NATIONALUM', 'NAUKRI', 'NAVA',
    'NAVKARCORP', 'NAVKARURB', 'NAVNETEDUL', 'NAZARA', 'NBCC', 'NBIFIN', 'NCC', 'NCLIND', 'NDL', 'NDLVENTURE',
    'NDRAUTO', 'NDTV', 'NECCLTD', 'NECLIFE', 'NELCAST', 'NELCO', 'NEOGEN', 'NEPACL', 'NESCO', 'NESTLEIND',
    'NETF', 'NETWEB', 'NETWORK18', 'NEWAGE', 'NEWERA', 'NEWGEN', 'NEXT30ADD', 'NEXT50', 'NEXT50IETF', 'NGLFINE',
    'NGIL', 'NH', 'NHIT', 'NHPC', 'NIACL', 'NIBE', 'NIITLTD', 'NIITMTS', 'NILAINFRA', 'NILASPACES',
    'NILKAMAL', 'NINSYS', 'NIPPOBATRY', 'NITCO', 'NITINSPIN', 'NITIRAJ', 'NIVABUPA', 'NKIND', 'NLCINDIA', 'NMDC',
    'NOCIL', 'NOIDATOLL', 'NORBTEAEXP', 'NOVAAGRI', 'NPBET', 'NPST', 'NRL', 'NSLNISP', 'NTPC', 'NTPCGREEN',
    'NUCLEUS', 'NUVAMA', 'NUVOCO', 'NV20', 'NV20BEES', 'NV20IETF', 'NYKAA', 'OBCL', 'OBEROIRLTY', 'OCCL',
    'OCCLLTD', 'OFSS', 'OIL', 'OILCOUNTUB', 'OLECTRA', 'OMAXAUTO', 'OMAXE', 'OMFREIGHT', 'OMINFRAL', 'ONGC',
    'ONEPOINT', 'ONELIFECAP', 'ONESOURCE', 'ONMOBILE', 'ONWARDTEC', 'OPTIEMUS', 'ORBTEXP', 'ORCHASP', 'ORCHPHARMA', 'ORICONENT',
    'ORIENTALTL', 'ORIENTBELL', 'ORIENTCEM', 'ORIENTCER', 'ORIENTELEC', 'ORIENTHOT', 'ORIENTLTD', 'ORIENTPPR', 'ORIENTTECH', 'ORKLAINDIA',
    'ORISSAMINE', 'OSIAHYPER', 'OSWALAGRO', 'OSWALGREEN', 'OSWALMIN', 'OSWALSEEDS', 'OAL', 'PAGEIND', 'PAISALO', 'PALASHSECU',
    'PALREDTEC', 'PANACEABIO', 'PANAMAPET', 'PANSARI', 'PAR', 'PARACABLES', 'PARADEEP', 'PARAGMILK', 'PARAS', 'PARKHOTELS',
    'PARSVNATH', 'PASHUPATI', 'PASUPTAC', 'PATANJALI', 'PATELENG', 'PATINTLOG', 'PATELRMART', 'PATNJALI', 'PAYTM', 'PCBL',
    'PCJEWELLER', 'PDSL', 'PDMJEPAPER', 'PEARLPOLY', 'PENIND', 'PENINLAND', 'PERSISTENT', 'PETRONET', 'PFC', 'PFIZER',
    'PGEL', 'PGHH', 'PGHL', 'PGIL', 'PHARMABEES', 'PHOENIXLTD', 'PIDILITIND', 'PIGL', 'PILITA', 'PIONEEREMB',
    'PITTIENG', 'PIXTRANS', 'PLASTIBLEN', 'PLATIND', 'PLAZACABLE', 'PNBGILTS', 'PNBHOUSING', 'PNC', 'PNCINFRA', 'PNB',
    'PODDARMENT', 'POKARNA', 'POLYCAB', 'POLYMED', 'POLYPLEX', 'PONNIERODE', 'POONAWALLA', 'POWERGRID', 'POWERINDIA', 'POWERMECH',
    'PPAP', 'PPL', 'PPLPHARMA', 'PRAENG', 'PRAJIND', 'PRAKASH', 'PRAKASHSTL', 'PRECAM', 'PRECOT', 'PREMIER',
    'PREMIERENE', 'PREMIERPOL', 'PRESTIGE', 'PRICOLLTD', 'PRIMESECU', 'PRIMO', 'PRINCEPIPE', 'PRITI', 'PRITIKAUTO', 'PRIVISCL',
    'PROSTARM', 'PROTEAN', 'PROZONER', 'PRSMJOHNSN', 'PRUDENT', 'PRUDMOULI', 'PSB', 'PSPPROJECT', 'PSUBANK', 'PSUBANKADD',
    'PSUBNKBEES', 'PSUBNKIETF', 'PTC', 'PTCIL', 'PTL', 'PUNJABCHEM', 'PURVA', 'PVP', 'PVRINOX', 'QPOWER',
    'QGOLDHALF', 'QUESS', 'QUICKHEAL', 'RACE', 'RACLGEAR', 'RADAAN', 'RADHIKAJWE', 'RADIANTCMS', 'RADICO',
    'RADIOCITY', 'RAILTEL', 'RAIN', 'RAINBOW', 'RAJESHEXPO', 'RAJMET', 'RAJOOENG', 'RAJRATAN', 'RAJSREESUG', 'RAJTV',
    'RALLIS', 'RAMANEWS', 'RAMAPHO', 'RAMARAJU', 'RAMASTEEL', 'RAMCOIND', 'RAMCOSYS', 'RAMKY', 'RAMRAT', 'RANASUG',
    'RATEGAIN', 'RATNAMANI', 'RATNAVEER', 'RAYMOND', 'RAYMONDLSL', 'RAYMONDREL', 'RBA', 'RBLBANK', 'RBZJEWEL', 'RCF',
    'RECLTD', 'REDINGTON', 'REDTAPE', 'REFEX', 'REGENCERAM', 'RELIABLE', 'RELIANCE', 'RELIGARE', 'RELINFRA', 'REMSONSIND',
    'RENUKA', 'REPL', 'REPRO', 'RESPONIND', 'RHFL', 'RHIM', 'RHL', 'RHETAN', 'RICOAUTO', 'RITCO',
    'RITES', 'RKDL', 'RKEC', 'RKFORGE', 'RKPURAM', 'RLF', 'RML', 'RMDRIP', 'RNAVAL', 'ROHLTD',
    'ROLEXRINGS', 'ROLLT', 'ROML', 'ROSSARI', 'ROSSELLIND', 'ROSSTECH', 'ROTO', 'ROUTE', 'RPGLIFE', 'RPPL',
    'RPSGVENT', 'RRKABEL', 'RSSOFTWARE', 'RSTL', 'RSWM', 'RSYSTEMS', 'RTNINDIA', 'RTNPOWER', 'RUBFILA', 'RUBICON',
    'RUCHINFRA', 'RUCHIRA', 'RUPA', 'RUSHIL', 'RVHL', 'RVNL', 'S&SPOWER', 'SABEVENTS', 'SADBHAV', 'SADBHIN',
    'SAFARI', 'SAGCEM', 'SAGARDEEP', 'SAGILITY', 'SAHYADRI', 'SAIL', 'SAKHTISUG', 'SAKSOFT', 'SAKUMA', 'SALASAR',
    'SALONA', 'SALSTEEL', 'SALZERELEC', 'SAMBHAAV', 'SAMBHV', 'SAMHI', 'SAMMAANCAP', 'SAMPANN', 'SANATHAN', 'SANDESH',
    'SANDHAR', 'SANDUMA', 'SANGAMIND', 'SANGHIIND', 'SANGHVIMOV', 'SANGINITA', 'SANOFI', 'SANOFICONR', 'SANSERA', 'SANSTAR',
    'SAPPHIRE', 'SARDAEN', 'SAREGAMA', 'SARLAPOLY', 'SASKEN', 'SASTASUNDR', 'SATIA', 'SATIN', 'SAURASHCEM', 'SBC',
    'SBFC', 'SBGLP', 'SBHL', 'SBICARD', 'SBILIFE', 'SBIN', 'SBISILVER', 'SBNI', 'SCHEFFLER', 'SCHNEIDER',
    'SCI', 'SCILAL', 'SCODATUBES', 'SEAMECLTD', 'SECMARK', 'SECURKLOUD', 'SELAN', 'SEMAC', 'SENCO', 
    'SEPC', 'SEPOWER', 'SEQUENT', 'SERVOTECH', 'SETCO', 'SETF10GILT', 'SETFGOLD', 'SETFNIF50', 'SETFNIFBK',
    'SETFNN50', 'SETUINFRA', 'SEYAIND', 'SFL', 'SGIL', 'SGMART', 'SGL', 'SGLTL', 'SHAHALLOYS', 'SHAH',
    'SHAILY', 'SHAKTIPUMP', 'SHALBY', 'SHALPAINTS', 'SHANKARA', 'SHANTIGEAR', 'SHANTIGOLD', 'SHANTI', 'SHARDACROP', 'SHARDAMOTR',
    'SHAREINDIA', 'SHEKHAWATI', 'SHEMAROO', 'SHILPAMED', 'SHIVAMAUTO', 'SHIVALIK', 'SHIVAMILLS', 'SHIVATEX', 'SHK', 'SHOPERSTOP',
    'SHOPEE', 'SHORE', 'SHREDIGCEM', 'SHREECEM', 'SHREEPUSHK', 'SHREERAMA', 'SHRENIK', 'SHREYANIND', 'SHRINIWAS', 'SHRIPISTON',
    'SHRIRAMFIN', 'SHRIRAMPPS', 'SHYAMCENT', 'SHYAMMETL', 'SHYAMTEL', 'SIEMENS', 'SIGACHI', 'SIGIND', 'SIGNATURE', 'SIGNPOST',
    'SIKKO', 'SIL', 'SILGO', 'SILINV', 'SILLYMONKS', 'SILVER', 'SILVER1', 'SILVER360', 'SILVERADD', 'SILVERAG',
    'SILVERBEES', 'SILVERCASE', 'SILVERETF', 'SILVERIETF', 'SIMBHALS', 'SIMPLEXINF', 'SINDHUTRAD', 'SINTERCOM', 'SIRCA', 'SIS',
    'SIYSIL', 'SJS', 'SJVN', 'SKFINDIA', 'SKMEGGPROD', 'SKP', 'SKYGOLD', 'SKIPPER', 'SKMEGGPROD', 'SMARTLINK',
    'SMARTWORKS', 'SMCGLOBAL', 'SMLISUZU', 'SMLMAH', 'SMLT', 'SMSLIFE', 'SMSPHARMA', 'SNXT30BEES', 'SNOWMAN', 'SOBHA',
    'SOFTTECH', 'SOLARINDS', 'SOLARA', 'SOLARWORLD', 'SOLEX', 'SOMANYCERA', 'SOMATEX', 'SOMICONVEY', 'SONACOMS', 'SONAMLTD',
    'SONATSOFTW', 'SORAL', 'SOUTHBANK', 'SOUTHWEST', 'SPAL', 'SPANDANA', 'SPECIALITY', 'SPECTRUM', 'SPENCERS', 'SPIC',
    'SPLIL', 'SPMLINFRA', 'SPORTKING', 'SPARC', 'SPLPETRO', 'SPLIL', 'SREEL', 'SRF', 'SRGHFL', 'SRHHYPOLTD',
    'SRM', 'SSDL', 'SSTL', 'STANLEY', 'STARCEMENT', 'STARHEALTH', 'STARPAPER', 'STARTECK', 'STEADFAST', 'STEELCAS',
    'STEELCITY', 'STEELXIND', 'STEL', 'STERTOOLS', 'STLTECH', 'STOVEKRAFT', 'STYL', 'STYLAMIND', 'STYRENIX', 'SUBEXLTD',
    'SUBROS', 'SUDARSCHEM', 'SUKHJITS', 'SULA', 'SUMICHEM', 'SUMIT', 'SUMMITSEC', 'SUNCLAY', 'SUNDRMBRAK', 'SUNDRMFAST',
    'SUNFLAG', 'SUNPHARMA', 'SUNTECK', 'SUNTV', 'SUPERHOUSE', 'SUPERSPIN', 'SUPRAJIT', 'SUPREME', 'SUPREMEIND', 'SUPRIYA',
    'SURAJEST', 'SURAJLTD', 'SURAKSHA', 'SURANASOL', 'SURANAT&P', 'SURYALAXMI', 'SURYAROSNI', 'SURYODAY', 'SUTLEJTEX', 'SUVEN',
    'SUVIDHAA', 'SUYOG', 'SUZLON', 'SVLL', 'SVPGLOB', 'SWANDEF', 'SWANCORP', 'SWARAJENG', 'SWELECTES', 'SWIGGY',
    'SYMPHONY', 'SYNCOMF', 'SYNGENE', 'SYRMA', 'SYSTMTXC', 'TAJGVK', 'TALBROAUTO', 'TANLA', 'TARACHAND', 'TARC',
    'TARMAT', 'TARSONS', 'TASTYBITE', 'TATACAP', 'TATACHEM', 'TATACOMM', 'TATACONSUM', 'TATAELXSI', 'TATAINVEST', 'TATAMOTORS',
    'TATAPOWER', 'TATATECH', 'TATAGOLD', 'TATASILV', 'TATVA', 'TBOTEK', 'TBZ', 'TCI', 'TCIEXP', 'TCIFINANCE',
    'TCPLPACK', 'TCS', 'TDPOWERSYS', 'TEAMLEASE', 'TECH', 'TECHM', 'TECHNOE', 'TEGA', 'TEJASNET', 'TEMBO',
    'TEXINFRA', 'TEXMOPIPES', 'TEXRAIL', 'TFCILTD', 'TFL', 'TGBHOTELS', 'THEINVEST', 'THEJO', 'THELEELA', 'THEMISMED',
    'THERMAX', 'THOMASCOOK', 'THOMASCOTT', 'THYROCARE', 'TIGERLOGS', 'TIINDIA', 'TIJARIA', 'TIL', 'TIMETECHNO', 'TIMESGTY',
    'TIMKEN', 'TINNARUBR', 'TIPSFILMS', 'TIPSMUSIC', 'TIPSINDLTD', 'TIRUMALCHM', 'TIRUPATIFL', 'TITAGARH', 'TITAN', 'TI',
    'TMB', 'TNIDETF', 'TNPL', 'TNPETRO', 'TNTELE', 'TOKYOPLAST', 'TOLINS', 'TOP10ADD', 'TORNTPHARM', 'TORNTPOWER',
    'TOTAL', 'TOUCHWOOD', 'TPLPLASTEH', 'TRACXN', 'TRANSRAILL', 'TRANSWORLD', 'TRAVELFOOD', 'TREEHOUSE', 'TRENT', 'TRF',
    'TRIDENT', 'TRIGYN', 'TRIL', 'TRITURBINE', 'TRIVENI', 'TRUALT', 'TRU', 'TTKHLTCARE', 'TTKPRESTIG', 'TTL',
    'TTML', 'TV18BRDCST', 'TVSELECT', 'TVSMOTOR', 'TVSSCS', 'TVSSRICHAK', 'TVTODAY', 'TVVISION', 'TWL', 'UBL',
    'UCAL', 'UCOBANK', 'UDS', 'UFLEX', 'UFO', 'UGARSUGAR', 'UGROCAP', 'UJJIVANSFB', 'ULTRACEMCO', 'UMAEXPORTS',
    'UMIYA-MRO', 'UMANGDAIRY', 'UMESLTD', 'UNICHEMLAB', 'UNIDT', 'UNIECOM', 'UNIONBANK', 'UNIONGOLD', 'UNIENTER', 'UNIPARTS',
    'UNITECH', 'UNITEDPOLY', 'UNITEDTEA', 'UNITDSPR', 'UNIVASTU', 'UNIVCABLES', 'UNIVPHOTO', 'UNOMINDA', 'UPL', 'URAVIDEF',
    'URBANCO', 'URJA', 'USHAMART', 'UTIAMC', 'UTIBANKETF', 'UTINEXT50', 'UTINIFTETF', 'UTISENSETF', 'UTISXN50', 'UTKARSHBNK',
    'UTTAMSUGAR', 'UYFINCORP', 'V2RETAIL', 'VADILALIND', 'VAIBHAVGBL', 'VAISHALI', 'VAKRANGEE', 'VALIANTLAB', 'VALIANTORG', 'VARROC',
    'VASWANI', 'VBL', 'VCL', 'VEDL', 'VEEDOL', 'VENKEYS', 'VENTIVE', 'VENUSREM', 'VENUSPIPES', 'VERANDA',
    'VERTOZ', 'VESUVIUS', 'VETO', 'VGUARD', 'VHLTD', 'VIDHIING', 'VIJAYA', 'VIJIFIN', 'VIKASECO', 'VIKASLIFE',
    'VIKRAMSOLR', 'VIMTALABS', 'VINATIORGA', 'VINDHYATEL', 'VINEETLAB', 'VINNY', 'VINYLINDIA', 'VIPCLOTHNG', 'VIPIND', 'VIPULLTD',
    'VIRINCHI', 'VISAKAIND', 'VISASTEEL', 'VISHNU', 'VISHWARAJ', 'VIVIDHA', 'VLEGOV', 'VLSFINANCE', 'VMART', 'VMSTMT',
    'VOLTAMP', 'VOLTAS', 'VPRPL', 'VRAJ', 'VRLLOG', 'VSSL', 'VSTIND', 'VSTTILLERS', 'VTL', 'WAAREEENER',
    'WAAREERTL', 'WABAG', 'WALCHANNAG', 'WANBURY', 'WEALTH', 'WEBELSOLAR', 'WEIZMANIND', 'WEL', 'WELCORP', 'WELENT',
    'WELSPUNLIV', 'WENDT', 'WESTLIFE', 'WHEELS', 'WHIRLPOOL', 'WILLAMAGOR', 'WINDLAS', 'WINDMACHIN', 'WINMORE', 'WINSOME',
    'WIPRO', 'WOCKPHARMA', 'WONDERLA', 'WORTH', 'WORTHPERI', 'WSI', 'XCHANGING', 'XELPMOC', 'XPROINDIA', 'XTGLOBAL',
    'YAARI', 'YASHO', 'YATHARTH', 'YATRA', 'YESBANK', 'YUKEN', 'ZAGGLE', 'ZEELEARN', 'ZEEL', 'ZEEMEDIA',
    'ZENITHEXPO', 'ZENSARTECH', 'ZENTEC', 'ZFCVINDIA', 'ZIMLAB', 'ZODIACLOTH', 'ZODIAC', 'ZOMATO', 'ZOTA', 'ZUARI',
    'ZUARIIND', 'ZYDUSLIFE', 'ZYDUSWELL']
